#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""gen_mapgrade.py - generate the per-map colour-grade lookup cfg from grade_profiles.tsv.

WHY THIS EXISTS
    docs/tools/grade_profiles.tsv holds the per-map colour-grade multipliers (expo/contrast/sat/temp
    over the HZM ACES baseline) for all 65 coop maps. Nothing read it. This tool turns that DATA table
    into a tiny server-side lookup cfg that coop_mod/mapgrade.scr reads at map load and publishes to
    each client as the packed cvar coop_mapGrade (see coop_mod/mapgrade.scr, cgame CG_CoopMapGradeThink,
    and renderergl2 RB_ToneMap's r_ppMap* layer).

    The cfg is GENERATED, never hand-edited: the grade table is the single source of truth, and a
    hand-kept copy would rot (OpenWolf: anything derivable from a table must be derived).

OUTPUT
    hzm-mohaa-coop-mod/coop_mod/cfg/mapgrade.cfg - one line per map:
        set coop_mg_<map> "<expo> <contrast> <sat> <temp>"
    Written CRLF (matching the other cfgs in that directory). coop_mg_* are non-archived server-side
    lookup cvars (not coop_mp*, so check_mp_isolation is unaffected); coop_mod/mapgrade.scr execs this
    cfg once per server session and reads coop_mg_<current map>.

USAGE
    python docs/tools/gen_mapgrade.py            write coop_mod/cfg/mapgrade.cfg
    python docs/tools/gen_mapgrade.py --check    exit 1 if the committed cfg no longer matches the tsv
"""
import argparse
import os
import sys

DEV = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
TSV = os.path.join(DEV, "docs", "tools", "grade_profiles.tsv")
CFG = os.path.join(DEV, "hzm-mohaa-coop-mod", "coop_mod", "cfg", "mapgrade.cfg")


def rows():
    out = []
    with open(TSV, encoding="latin-1") as f:
        for line in f:
            line = line.rstrip("\r\n")
            if not line or line.startswith("#"):
                continue
            cols = line.split("\t")
            if cols[0] == "map":
                continue  # header
            if len(cols) < 5:
                sys.exit("gen_mapgrade: malformed row (need >=5 columns): %r" % line)
            mp = cols[0].strip().lower()
            vals = [cols[i].strip() for i in range(1, 5)]  # expo, contrast, sat, temp
            for v in vals:
                float(v)  # assert numeric - a bad cell must fail the build, not ship a broken grade
            out.append((mp, vals))
    # stable, de-duplicated
    seen = set()
    uniq = []
    for mp, vals in out:
        if mp in seen:
            sys.exit("gen_mapgrade: duplicate map row %r" % mp)
        seen.add(mp)
        uniq.append((mp, vals))
    return uniq


def render(data):
    nl = "\r\n"
    lines = [
        "// GENERATED by docs/tools/gen_mapgrade.py from docs/tools/grade_profiles.tsv - DO NOT EDIT BY HAND.",
        "//   regenerate: python docs/tools/gen_mapgrade.py",
        "//   drift test: python docs/tools/gen_mapgrade.py --check   (exit 1 == stale)",
        "//",
        "// Per-map colour grade lookup, one non-archived cvar per coop map:",
        "//   coop_mg_<map> = \"<expo> <contrast> <sat> <temp>\"  (multipliers over the HZM ACES baseline).",
        "// coop_mod/mapgrade.scr execs this once per server session and publishes coop_mg_<current map>",
        "// to each client as the packed cvar coop_mapGrade. On by default; the player opt-out is the",
        "// client-only archived cvar r_ppMapGradeOn (a server cannot flip it).",
    ]
    for mp, vals in data:
        lines.append('set coop_mg_%s "%s"' % (mp, " ".join(vals)))
    return (nl.join(lines) + nl).encode("latin-1")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()

    text = render(rows())

    if a.check:
        cur = open(CFG, "rb").read() if os.path.exists(CFG) else b""
        if cur != text:
            print("gen_mapgrade: STALE - %s no longer matches the tsv; run python docs/tools/gen_mapgrade.py"
                  % os.path.relpath(CFG, DEV))
            return 1
        print("gen_mapgrade: OK (%d maps)" % text.count(b"set coop_mg_"))
        return 0

    with open(CFG, "wb") as f:
        f.write(text)
    print("wrote %s (%d maps)" % (os.path.relpath(CFG, DEV), text.count(b"set coop_mg_")))
    return 0


if __name__ == "__main__":
    sys.exit(main())
