#!/usr/bin/env python3
"""Generate coop_mod/mp_basebuild_stations.scr from basebuild_stations.tsv.

The station data was harvested from the real alienx/basebuild.scr (UBER-MODS-v8.00-MOHAA): each
BaseBuilder map calls `exec alienx/basebuild.scr::main <params>` once, then spawns its build stations
with `exec alienx/basebuild.scr::basebuild ( origin ) "model" <args>`. This emits two dispatch labels
the MP buildabase mode calls - bb_mainFor (the per-map main args) and bb_stationsFor (the station
spawns) - so the mode LOADS the real basebuild rather than reimplementing it.

Run:  python docs/tools/gen_basebuild_maps.py         (write)
      python docs/tools/gen_basebuild_maps.py check   (exit 1 if the .scr is stale)
"""
import sys, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TSV = os.path.join(ROOT, "docs", "tools", "basebuild_stations.tsv")
OUT = os.path.join(ROOT, "hzm-mohaa-coop-mod", "coop_mod", "mp_basebuild_stations.scr")


def rkey(m):
    """Runtime mapname key. The mohdm* deathmatch maps live in maps/DM/, so the engine's `mapname`
    cvar is "dm/mohdm1" (see mp_koth.scr); the SP campaign maps live in maps/ root, so theirs is bare."""
    return "dm/" + m if re.match(r"^mohdm\d", m) else m


def load():
    mains, stations = {}, {}
    for line in open(TSV, encoding="utf-8"):
        line = line.rstrip("\n")
        if not line or (line.startswith("#") and not line.startswith("# map")):
            continue
        if line.startswith("# map"):
            _, m, _, params = line.split("\t")
            mains[m] = params.strip()
            stations.setdefault(m, [])
        else:
            m, args = line.split("\t", 1)
            stations.setdefault(m, []).append(args.strip())
    return mains, stations


def build():
    mains, stations = load()
    maps = sorted(stations)
    L = []
    L.append("// GENERATED by docs/tools/gen_basebuild_maps.py from basebuild_stations.tsv. Do NOT hand-edit.")
    L.append("// Per-map BaseBuilder station data, harvested verbatim from the real alienx/basebuild.scr (UberMod")
    L.append("// v8.00). coop_mod/mp_buildabase.scr LOADS the real basebuild mod - it calls bb_mainFor to get a map's")
    L.append("// basebuild::main args, then bb_stationsFor to spawn that map's build stations (the exact")
    L.append("// `exec alienx/basebuild.scr::basebuild ( origin ) \"model\" ...` placements the mod authors made).")
    L.append("// MP-only (coop_mod/mp*.scr, gated by the buildabase mode which needs level.coop_mpRun); never touches coop.")
    L.append("")
    # bb_mainFor: return the map's basebuild::main args, or "" if the map has no BaseBuilder data.
    L.append("//return the basebuild::main args for a map, or \"\" when the map is not a BaseBuilder map.")
    L.append("bb_mainFor local.map:{")
    L.append("\tlocal.p = \"\"")
    for m in maps:
        L.append('\tif( local.map == "%s" ){ local.p = "%s" }' % (rkey(m), mains.get(m, "800 1000 500 1 1 0 0 0")))
    L.append("}end local.p")
    L.append("")
    L.append("")
    # bb_stationsFor: spawn every station for the map (the real basebuild calls).
    L.append("//spawn every build station for a map (the real alienx/basebuild.scr::basebuild placements).")
    L.append("bb_stationsFor local.map:{")
    L.append("\tswitch( local.map ){")
    for m in maps:
        L.append('\tcase "%s":' % rkey(m))
        for st in stations[m]:
            L.append("\t\texec alienx/basebuild.scr::basebuild %s" % st)
        L.append("\t\tbreak")
    L.append("\t}")
    L.append("}end")
    L.append("")
    return "\n".join(L)


def main():
    text = build()
    if len(sys.argv) > 1 and sys.argv[1] == "check":
        cur = open(OUT, encoding="latin-1").read() if os.path.exists(OUT) else ""
        if cur != text:
            print("STALE: mp_basebuild_stations.scr differs from generator output")
            sys.exit(1)
        print("OK: mp_basebuild_stations.scr matches generator")
        return
    open(OUT, "w", encoding="latin-1", newline="\n").write(text)
    nst = sum(len(v) for v in load()[1].values())
    print("wrote %s (%d maps, %d stations)" % (os.path.relpath(OUT, ROOT), len(load()[1]), nst))


if __name__ == "__main__":
    main()
