#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Generate the Gun Game FFA tier ladder script from docs/tools/mp_gungame_tiers.tsv.

WHY THIS EXISTS (and why it is its own tool)
    The Gun Game weapon ladder is DATA - an ordered list of weapon tiks, ammo classes and display
    names - while coop_mod/mp_gungame.scr is LOGIC. Keeping the ladder in a .tsv behind a generator
    means a retune is a one-line table edit that cannot introduce a parse killer (the emitter writes
    ASCII + LF and asserts no empty right-hand side, TRAPS T1 / bug-1908), and `check` byte-compares
    the regenerated file against disk so a hand-edit or a stale build cannot ship (same discipline as
    gen_loadout.py and gen_mp_armory.py, both build gates).

    It writes exactly ONE file and touches nothing else:
        hzm-mohaa-coop-mod/coop_mod/mp_gungame_tiers.scr

    That output is an MP file (coop_mod/mp*.scr is in MP_MANIFEST): it is read ONLY by
    coop_mod/mp_gungame.scr, names no coop cvar / coop_lo / ui/loadout token, and the emitter
    asserts as much so a coop leak can never be generated.

    python docs/tools/gen_mp_gungame.py check   # regenerate in memory + byte-compare (exit 1 = drift)
    python docs/tools/gen_mp_gungame.py build   # write the file
"""
import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
MOD = os.path.join(ROOT, "hzm-mohaa-coop-mod")
TSV = os.path.join(os.path.dirname(os.path.abspath(__file__)), "mp_gungame_tiers.tsv")
OUT = os.path.join(MOD, "coop_mod", "mp_gungame_tiers.scr")

COLUMNS = ["tier", "give", "ammo", "ammoN", "name", "bashonly"]
AMMO_CLASSES = {"rifle", "smg", "mg", "shotgun", "pistol", "heavy", "grenade"}


def load_rows():
    rows = []
    with io.open(TSV, "r", encoding="ascii") as fh:
        header = None
        for raw in fh:
            line = raw.rstrip("\n").rstrip("\r")
            if line == "" or line.startswith("#"):
                continue
            cells = line.split("\t")
            if header is None:
                header = cells
                if header != COLUMNS:
                    raise SystemExit("gen_mp_gungame: header %r != %r" % (header, COLUMNS))
                continue
            if len(cells) != len(COLUMNS):
                raise SystemExit("gen_mp_gungame: row has %d cells, want %d: %r" % (len(cells), len(COLUMNS), cells))
            rows.append(dict(zip(COLUMNS, cells)))
    return rows


def check_invariants(rows):
    if not rows:
        raise SystemExit("gen_mp_gungame: no tiers in the table")
    for i, r in enumerate(rows):
        if int(r["tier"]) != i:
            raise SystemExit("gen_mp_gungame: tiers must be 0..N-1 with no gaps; row %d has tier %s" % (i, r["tier"]))
        if not re.match(r"^models/weapons/[A-Za-z0-9_]+\.tik$", r["give"]):
            raise SystemExit("gen_mp_gungame: tier %d give %r is not a models/weapons/*.tik" % (i, r["give"]))
        if r["ammo"] not in AMMO_CLASSES:
            raise SystemExit("gen_mp_gungame: tier %d ammo %r not one of %s" % (i, r["ammo"], sorted(AMMO_CLASSES)))
        int(r["ammoN"])  # must parse
        if r["bashonly"] not in ("0", "1"):
            raise SystemExit("gen_mp_gungame: tier %d bashonly must be 0/1" % i)
        if not r["name"]:
            raise SystemExit("gen_mp_gungame: tier %d has an empty name" % i)
    # Exactly one bash-only tier and it is the LAST one (M7).
    bash = [i for i, r in enumerate(rows) if r["bashonly"] == "1"]
    if bash != [len(rows) - 1]:
        raise SystemExit("gen_mp_gungame: exactly one bash-only tier is required and it must be the final tier (got %r)" % bash)
    # The bash-only tier issues zero reserve ammo (pistol-whip only).
    if int(rows[-1]["ammoN"]) != 0:
        raise SystemExit("gen_mp_gungame: the final bash-only tier must grant ammoN 0 (pistol-whip only)")


def render(rows):
    n = len(rows)
    L = []
    L.append("//=========================================================================")
    L.append("// MP_GUNGAME_TIERS.SCR - GENERATED by docs/tools/gen_mp_gungame.py from")
    L.append("// docs/tools/mp_gungame_tiers.tsv. DO NOT EDIT BY HAND - run:")
    L.append("//   python docs/tools/gen_mp_gungame.py build")
    L.append("//")
    L.append("// The Gun Game weapon ladder (FFA, one shared ladder - gt1 has no sides). Weak -> strong,")
    L.append("// ending in a bash/pistol-whip-only final tier (decision M7). coop_mod/mp_gungame.scr reads")
    L.append("// it ONCE and caches it in level.coop_mpGGTiers / level.coop_mpGGTierCount.")
    L.append("//")
    L.append("// This is an MP file (coop_mod/mp*.scr is in MP_MANIFEST): it names no coop cvar or tree and")
    L.append("// is only ever read by mp_gungame.scr, which mp.scr dispatches under level.coop_mpRun.")
    L.append("//=========================================================================")
    L.append("")
    L.append("//The number of tiers in the ladder. The final tier (index count-1) is bash/pistol-whip only.")
    L.append("tier_count:{")
    L.append("}end " + str(n))
    L.append("")
    L.append("//The ordered ladder as an array of dicts, index 0..count-1:")
    L.append("//  [i][\"give\"]  weapon tik   [i][\"ammo\"] ammo class   [i][\"ammoN\"] reserve rounds")
    L.append("//  [i][\"name\"]  display name  [i][\"bashonly\"] 1 on the final pistol-whip tier only")
    L.append("tiers:{")
    for i, r in enumerate(rows):
        L.append("\tlocal.t[" + str(i) + "][\"give\"] = \"" + r["give"] + "\"")
        L.append("\tlocal.t[" + str(i) + "][\"ammo\"] = \"" + r["ammo"] + "\"")
        L.append("\tlocal.t[" + str(i) + "][\"ammoN\"] = " + str(int(r["ammoN"])))
        L.append("\tlocal.t[" + str(i) + "][\"name\"] = \"" + r["name"] + "\"")
        L.append("\tlocal.t[" + str(i) + "][\"bashonly\"] = " + r["bashonly"])
    L.append("}end local.t")
    L.append("")
    return "\n".join(L)


def assert_clean(text):
    if text[:1] == "﻿":
        raise SystemExit("gen_mp_gungame: output has a BOM")
    try:
        text.encode("ascii")
    except UnicodeEncodeError as e:
        raise SystemExit("gen_mp_gungame: output is not ASCII: %s" % e)
    low = text.lower()
    for bad in ("coop_lo", "ui/loadout/", "vstr", "—"):
        if bad in low:
            raise SystemExit("gen_mp_gungame: output names a banned token %r" % bad)
    # no coop_ name that is not coop_mp* or the coop_mod/ path prefix (this file must never touch coop state)
    for m in re.finditer(r"coop_(?!mp|mod\b)\w*", low):
        raise SystemExit("gen_mp_gungame: output names a non-MP coop token %r" % m.group(0))
    for i, ln in enumerate(text.split("\n"), 1):
        if re.search(r"=\s*$", ln) and not ln.strip().startswith("//"):
            raise SystemExit("gen_mp_gungame: %s:%d has an empty right-hand side (bug-1908)" % (OUT, i))


def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else "check"
    if mode not in ("build", "check"):
        print(__doc__)
        return 2
    rows = load_rows()
    check_invariants(rows)
    text = render(rows)
    assert_clean(text)
    rel = os.path.relpath(OUT, ROOT)

    if mode == "build":
        d = os.path.dirname(OUT)
        if not os.path.isdir(d):
            os.makedirs(d)
        io.open(OUT, "wb").write(text.encode("ascii"))
        print("wrote %s (%d tiers, LF, ASCII)" % (rel, len(rows)))
        return 0

    if not os.path.exists(OUT):
        print("%s : MISSING - run: python docs/tools/gen_mp_gungame.py build" % rel)
        return 1
    disk = io.open(OUT, "rb").read()
    want = text.encode("ascii")
    if disk == want:
        print("%s : EXACT REPRODUCTION (%d tiers)" % (rel, len(rows)))
        return 0
    print("%s : MISMATCH - run: python docs/tools/gen_mp_gungame.py build" % rel)
    return 1


if __name__ == "__main__":
    sys.exit(main())
