#!/usr/bin/env python3
"""Generate coop_mod/aircraft_envelope.scr - the per-map flight envelope for the coop aircraft call-ins.

Source: the retail BSPs (read only, aircraft_bsp.py) + docs/tools/fog_profiles.tsv. Never hand-edit the output.
Design: docs/proposals/aircraft_2026-10-05/PLAN.md section 5.

Per map (heights in game units; 16 u = 1 ft):
  g     median outdoor ground z          sky   lowest sky over the outdoor play area (z, 10th percentile)
  fog   fog distance (0 = none)          obs   95th-percentile structure/terrain top (z)
  cls   A open / B fog-limited / C sky too low (fly above it, broadcast) / D no usable sky (audio + effects only)
  yaw   heading of the longest straight run at flight height
  hc    C-47 height above ground         hb    dive-bomber entry height above ground
Rules: floor = max(obstacles + 384, 640); fog cap = 0.7 x fog (the cgame draws aircraft through the outer fog);
prefer flying under the sky brush when it leaves room, else above it (class C).

Usage:
    python gen_aircraft_envelope.py build    # write the .scr
    python gen_aircraft_envelope.py check    # regenerate in memory, byte-compare, exit 1 on drift
"""
import math, os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import aircraft_bsp as E  # noqa: E402

OUT = os.path.join(HERE, "..", "..", "hzm-mohaa-coop-mod", "coop_mod", "aircraft_envelope.scr")


def num(v):
    v = int(round(v))
    return ("( 0 - %d )" % -v) if v < 0 else str(v)


def row(m, fogs):
    r = E.analyse(m, fogs)
    if "g50" not in r or r.get("outdoor", 0) < 40:
        return {"map": m, "cls": "D", "g": 0, "sky": 0, "fog": r.get("fog", 0) or 0, "obs": 0, "yaw": 0, "hc": 0, "hb": 0}
    g, F = r["g50"], (r["fog"] or 0)
    obs = r["top95"] if r["top95"] == r["top95"] else g
    clr = r["c10"] - g
    floor = max(obs - g + 384, 640)
    fogcap = 0.7 * F if F > 0 else 1e9
    hc = min(fogcap, 2400)
    cls = "A" if (F == 0 or F >= 6000) else "B"
    if clr - 128 >= floor + 200:
        hc = min(hc, clr - 128)
    elif hc > clr - 128:
        cls = "C"
    hc = max(hc, floor)
    hb = max(min(fogcap * 1.15, 3200, hc * 1.4), floor + 600)
    E.choose(r)
    return {"map": m, "cls": cls, "g": g, "sky": r["c10"], "fog": F, "obs": obs, "yaw": r.get("run_yaw", 0),
            "hc": hc, "hb": hb}


def render(rows):
    L = ["// GENERATED by docs/tools/gen_aircraft_envelope.py from the retail BSPs + docs/tools/fog_profiles.tsv.",
         "// DO NOT EDIT - edit the generator and run `python docs/tools/gen_aircraft_envelope.py build`.",
         "// Per-map flight envelope for coop_mod/aircraft.scr (docs/proposals/aircraft_2026-10-05).",
         "// Keys: g ground z, sky lowest sky z, fog distance, obs structure top z, cls A/B/C/D, yaw best run,",
         "//       hc C-47 height above ground, hb dive-bomber entry height above ground.",
         "",
         "row local.m:{",
         "\tlocal.r = NIL"]
    for r in rows:
        L.append('\tif( local.m == "%s" ){' % r["map"])
        L.append('\t\tlocal.r["g"] = %s' % num(r["g"]))
        L.append('\t\tlocal.r["sky"] = %s' % num(r["sky"]))
        L.append('\t\tlocal.r["fog"] = %s' % num(r["fog"]))
        L.append('\t\tlocal.r["obs"] = %s' % num(r["obs"]))
        L.append('\t\tlocal.r["cls"] = "%s"' % r["cls"])
        L.append('\t\tlocal.r["yaw"] = %s' % num(r["yaw"]))
        L.append('\t\tlocal.r["hc"] = %s' % num(r["hc"]))
        L.append('\t\tlocal.r["hb"] = %s' % num(r["hb"]))
        L.append('\t\tend local.r')
        L.append('\t}')
    L.append("}end local.r")
    return ("\r\n".join(L) + "\r\n").encode("ascii")


def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else "build"
    fogs = E.fog_rows()
    rows = [row(m, fogs) for m in E.MAPS]
    data = render(rows)
    if mode == "check":
        cur = open(OUT, "rb").read() if os.path.exists(OUT) else b""
        if cur != data:
            print("aircraft_envelope.scr is STALE - run build")
            return 1
        print("aircraft_envelope.scr up to date (%d maps)" % len(rows))
        return 0
    with open(OUT, "wb") as f:
        f.write(data)
    print("wrote", os.path.normpath(OUT), len(rows), "maps")
    for r in rows:
        print("  %-6s %s hc=%5d hb=%5d fog=%5d" % (r["map"], r["cls"], r["hc"], r["hb"], r["fog"]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
