"""Make the missing finish art for reload magazines that wear their OWN texture sheet.

WHY THIS EXISTS
---------------
gen_clip_skins.py gives a magazine the same finish shader the gun's own variant TIK uses for the
surface wearing that texture. That covers every magazine whose texture the gun body also wears - 9 of
them. Five (gun, texture) pairs are left over because their magazine is painted from a sheet the gun
never uses:

    m1clip      - Enfield, Springfield, Carcano   (the shared M1 clip sheet; the Garand DOES wear it,
                                                   which is why the Garand was already covered)
    barclip     - BAR
    mauserammo  - Kar98

For those the finish simply does not exist yet, so this tool makes it, reusing the two halves of the
system that already produced all 350 gun finishes rather than inventing a parallel look:

  * BAKED finishes (bloody + three camos) come from bake_skins.py's own functions, which split the
    base into low-frequency shading and high-frequency detail and replace only the hue - so screws
    and grain survive instead of being flooded over.
  * STAGE finishes (gold, chrome, blued) are pure shader: a GL_DST_COLOR/GL_ZERO multiply plus the
    shared env_sheen sphere map. They need NO art at all, which is why only 4 textures per pair get
    baked rather than 7.

Both the tint table and the shader emitter are IMPORTED from gen_skins.py, not copied. If the finish
palette is ever retuned, these magazines follow it automatically.

NAMING. Blocks are coop_skin_<gun>_<finish>_clip, in their own scripts/coop_clip_skins.shader. The
_clip suffix keeps them clear of the gun's own coop_skin_<gun>_<finish>[_N] blocks, which are indexed
by the gun's surface order and must not be disturbed.
"""

import io
import os
import re
import sys

# --- reuse the real tools rather than re-deriving their recipes -----------------------------------
HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
MOD = os.path.join(REPO, "hzm-mohaa-coop-mod")

_gs = io.open(os.path.join(HERE, "gen_skins.py"), encoding="utf-8").read()
# everything above the driver: constants, FINISHES, shader_block
exec(_gs.split("def shared_shader_names(")[0], globals())
_sb = _gs[_gs.index("def shader_block("):_gs.index("def variant_tik(")]
exec(_sb, globals())

_bs = io.open(os.path.join(HERE, "bake_skins.py"), encoding="utf-8").read()
exec(_bs.split('if __name__ ==')[0], globals())

OUT_SHADER = os.path.join(MOD, "scripts", "coop_clip_skins.shader")

# (gun stem, the magazine's own texture) - the five pairs gen_clip_skins.py cannot resolve.
PAIRS = [
    ("enfield",      "textures/models/weapons/m1garand/m1clip.tga"),
    ("springfield",  "textures/models/weapons/m1garand/m1clip.tga"),
    ("it_w_carcano", "textures/models/weapons/m1garand/m1clip.tga"),
    ("bar",          "textures/models/weapons/bar/barclip.tga"),
    ("kar98",        "textures/models/weapons/kar98/mauserammo.tga"),
]


def main():
    write = "--write" in sys.argv
    os.makedirs(os.path.join(MOD, "textures", "coop_skins"), exist_ok=True)

    # the shared sphere map every stage finish samples; harmless to re-emit, it is deterministic
    if write:
        make_envmap(os.path.join(MOD, "textures", "coop_skins", "env_sheen.tga"))       # noqa: F821

    blocks, baked = [], 0
    for gun, tex in PAIRS:
        stub = os.path.splitext(os.path.basename(tex))[0]
        if write:
            baked += bake_for(gun, [tex])                                               # noqa: F821
        for key, disp, kind, params in FINISHES:                                        # noqa: F821
            name = "coop_skin_%s_%s_clip" % (gun, key)
            if kind == "stage":
                blocks.append(shader_block(name, tex, kind, params))                    # noqa: F821
            else:
                src = "textures/coop_skins/%s/%s_%s.jpg" % (gun, stub, key)
                blocks.append(shader_block(name, src, kind, params))                    # noqa: F821
        print("  %-14s %-46s 7 shader(s)" % (gun, os.path.basename(tex)))

    hdr = (
        "// HZM coop [2026-09-01, bug-2241] FINISHES FOR MAGAZINES THAT WEAR THEIR OWN SHEET.\n"
        "// GENERATED by docs/tools/gen_clip_art.py - do not hand-edit, re-run the generator.\n"
        "//\n"
        "// gen_clip_skins.py hands a magazine whatever finish shader the gun's own variant TIK uses\n"
        "// for the surface wearing that texture. That works for every magazine painted from a sheet\n"
        "// the gun body also wears. These five are painted from a sheet the gun never uses - the\n"
        "// shared m1clip sheet, barclip, mauserammo - so no finish existed for them at all.\n"
        "//\n"
        "// The tint table and the shader emitter are IMPORTED from gen_skins.py, so if the finish\n"
        "// palette is retuned these follow it. Gold, chrome and blued are pure stages and need no\n"
        "// art; only bloody and the three camos are baked, by bake_skins.py's own functions.\n"
        "//\n"
        "// The _clip suffix keeps these clear of the gun's coop_skin_<gun>_<finish>[_N] blocks,\n"
        "// which are indexed by the GUN's surface order and must not be disturbed.\n"
    )
    text = hdr + "\n".join(blocks) + "\n"

    if write:
        open(OUT_SHADER, "wb").write(text.encode("ascii"))
        print("\n  wrote %s (%d blocks, %d baked textures)"
              % (os.path.relpath(OUT_SHADER, REPO), len(blocks), baked))
    else:
        print("\n  DRY RUN - %d blocks would be written; pass --write" % len(blocks))
    return 0


if __name__ == "__main__":
    sys.exit(main())
