"""
gen_gore_skins.py - composite the damage-tier blood skins for character surfaces.

WHY THIS FILE EXISTS AT ALL
---------------------------
scripts/coop_gore.shader opens with "GENERATED by scratchpad/gen_gore_skins.py - do not hand-edit,
re-run the generator" and that file no longer exists: it was written into a session scratchpad and
lost. 96 blood1 / 96 blood2 / 97 blood3 textures shipped from it and could not be extended, which is
why 11 campaign-spawned enemies still cannot bleed (bug-2202/bug-2203). This is the rebuild, in the
repo, with a byte-compare `check` mode so it cannot rot the same way twice.

WHAT A GORE SKIN IS
-------------------
sentient.cpp picks a damage tier and writes it as the SKIN INDEX on each surface. The TIKI declares
the ladder:

    surface tunic shader wehrmacht_soldat            <- tier 0, clean
    surface tunic shader wehrmacht_soldat_blood1     <- tier 1, light
    surface tunic shader wehrmacht_soldat_blood2     <- tier 2, heavy
    surface tunic shader wehrmacht_soldat_blood3     <- tier 3, gib

So each rung is a whole shader over a whole composited diffuse. docs/tools/gen_gore_tiks.py adds the
TIKI lines; this tool makes the textures and the shaders they point at.

THE NUMBERS ARE MEASURED, NOT INVENTED
--------------------------------------
Sampled from the shipped pair textures/models/human/britmaintt/SC_AL_brit_inf_pants_blood{1,2}.jpg
against its effective base: blood1 darkens ~1.8% of texels, blood2 ~15.8%, blending toward the mod's
blood colour authority #150200 fresh / (7,1,0) dried (_research/player_gore_research.md 6c). The
COVERAGE and ALPHA tables below reproduce that, so newly generated skins sit in the same family as
the ones already shipped rather than reading as a different pass.

THE BASE MUST BE THE ONE THE GAME ACTUALLY DRAWS. Character skins are overridden by the HD pack
(zzzzzz_hd_charskins.pk3 sorts after pak1), and the shipped blood textures are 1024x1024 to match it,
not 256x256. Compositing onto the retail original would ship a visibly lower-res wound skin that pops
when the tier changes. This resolves highest-resolution-wins, the same way the engine does.

DETERMINISTIC: the blotch RNG is seeded from the shader name, so a re-run reproduces the same image
and `check` is meaningful.

Usage:
  python docs/tools/gen_gore_skins.py --targets docs/generated/gore_missing.txt --list
  python docs/tools/gen_gore_skins.py --targets docs/generated/gore_missing.txt --write
  python docs/tools/gen_gore_skins.py --targets ... --check     # byte-compare, exit 1 on drift
"""

import argparse
import glob
import io
import math
import os
import random
import re
import sys
import zipfile

try:
    from PIL import Image, ImageDraw, ImageFilter
except ImportError:
    print("gen_gore_skins: Pillow is required (pip install pillow)")
    sys.exit(2)

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
MOD = os.path.join(REPO, "hzm-mohaa-coop-mod")
PAK_GLOB = r"G:\GOG\Medal of Honor - Allied Assault War Chest\*\*.pk3"
OUT_SHADER = os.path.join(MOD, "scripts", "coop_gore_gen.shader")

FRESH = (21, 2, 0)    # #150200 - the mod's blood colour authority
DRIED = (7, 1, 0)

# tier -> (coverage fraction, alpha range, blob radius range as a fraction of the texture)
TIERS = {
    "_blood1": (0.020, (0.10, 0.38), (0.010, 0.030)),
    "_blood2": (0.160, (0.25, 0.68), (0.018, 0.055)),
    "_blood3": (0.330, (0.40, 0.88), (0.025, 0.075)),
}

SURF_SKIP = re.compile(
    r"helmet|inside|outside|holster|ammobox|shell|gear|loadout|strap|pack|canteen|bayonet|knife|"
    r"granade|grenade|goggle|binocular|pouch|beret|hat$|cap$|armband|vest|map$", re.I)


# ----------------------------------------------------------------- pak / file resolution
_PAKS = None


def paks():
    global _PAKS
    if _PAKS is None:
        _PAKS = []
        for p in sorted(glob.glob(PAK_GLOB)):
            if "co-op_hzm" in os.path.basename(p):
                continue
            try:
                _PAKS.append((p, zipfile.ZipFile(p)))
            except Exception:
                pass
    return _PAKS


def read_text(path):
    local = os.path.join(MOD, path.replace("/", os.sep))
    if os.path.exists(local):
        return open(local, encoding="latin-1").read()
    for _p, z in paks():
        lo = {n.lower(): n for n in z.namelist()}
        if path.lower() in lo:
            return z.read(lo[path.lower()]).decode("latin-1")
    return None


def best_image(texpath):
    """Highest-resolution copy of a texture, mod first then paks - what the engine would draw."""
    stem = re.sub(r"\.(tga|jpg|jpeg|png)$", "", texpath.lower())
    best = None
    for ext in (".tga", ".jpg", ".jpeg", ".png"):
        cand = os.path.join(MOD, (stem + ext).replace("/", os.sep))
        if os.path.exists(cand):
            try:
                im = Image.open(cand).convert("RGB")
                if best is None or im.size[0] > best[0].size[0]:
                    best = (im, "mod:" + stem + ext)
            except Exception:
                pass
    for p, z in paks():
        lo = {n.lower(): n for n in z.namelist()}
        for ext in (".tga", ".jpg", ".jpeg", ".png"):
            k = stem + ext
            if k in lo:
                try:
                    im = Image.open(io.BytesIO(z.read(lo[k]))).convert("RGB")
                    if best is None or im.size[0] > best[0].size[0]:
                        best = (im, os.path.basename(p))
                except Exception:
                    pass
    return best


# ----------------------------------------------------------------- validation
def _assert_balanced(blocks):
    """Each emitted block must balance on its own, so a bad one gets NAMED rather than hidden."""
    bad = [(blk.splitlines()[0], blk.count("{"), blk.count("}"))
           for blk in blocks if blk.count("{") != blk.count("}")]
    if bad:
        for name, o, c in bad[:10]:
            print("    UNBALANCED %-40s %d open / %d close" % (name, o, c))
        raise SystemExit("refusing to write: %d unbalanced shader block(s)" % len(bad))


def _assert_parseable(text):
    """Re-parse the finished file the way the ENGINE parses it, before letting it out the door.

    renderergl2's ScanAndLoadShaderFiles walks name -> opening brace -> SkipBracedSection and, on any
    failure, discards the WHOLE FILE. So "brace-balanced overall" is not a strong enough test - it has
    to parse block by block. Reproducing that check here is the difference between a loud build failure
    and 70 silently missing shaders.
    """
    i, n, count = 0, len(text), 0
    while i < n:
        while i < n and text[i] in " \t\r\n":
            i += 1
        if i >= n:
            break
        if text.startswith("//", i):
            nl = text.find("\n", i)
            if nl < 0:
                break
            i = nl + 1
            continue
        j = i
        while j < n and text[j] not in " \t\r\n":
            j += 1
        name = text[i:j]
        k = j
        while k < n and text[k] in " \t\r\n":
            k += 1
        if k >= n or text[k] != "{":
            raise SystemExit("refusing to write: shader %r is not followed by an opening brace" % name)
        depth = 0
        while k < n:
            if text[k] == "{":
                depth += 1
            elif text[k] == "}":
                depth -= 1
                if depth == 0:
                    break
            k += 1
        if depth != 0:
            raise SystemExit("refusing to write: shader %r has no closing brace" % name)
        count += 1
        i = k + 1
    print("  engine-parse check OK - %d blocks parse the way renderergl2 parses them" % count)


def _assert_not_shrinking(n_new):
    """This tool REPLACES coop_gore_gen.shader; it does not merge into it.

    So it must always be run with the FULL target list. Running it over a subset silently deletes
    every block the subset does not cover, and the output looks perfectly healthy afterwards. That
    happened on 2026-08-31: a follow-up run over 104 TIKs replaced a 229-block file with 30, and the
    only symptom would have been gore quietly missing from two thirds of the cast.

    The correct target list is the union of the generated docs/generated/gore_missing.txt and every
    character TIK that already carries a "surface <s> shader <name>_blood<n>" rung.
    """
    if not os.path.exists(OUT_SHADER):
        return
    prev = open(OUT_SHADER, encoding="latin-1").read()
    n_old = len(re.findall(r"(?m)^[A-Za-z0-9_/.-]+[ \t]*\r?\n[ \t]*\{", prev))
    if n_new < n_old and not os.environ.get("GORE_ALLOW_SHRINK"):
        raise SystemExit(
            "refusing to write: this run produces %d blocks but the existing file has %d.\n"
            "  This tool REPLACES the file - run it with the FULL target list, not a subset.\n"
            "  Set GORE_ALLOW_SHRINK=1 if the reduction is genuinely intended." % (n_new, n_old))


# ----------------------------------------------------------------- shaders
def shader_bodies():
    """name -> raw body text, from every shader file we can see."""
    out = {}
    files = [f for f in glob.glob(os.path.join(MOD, "scripts", "*.shader"))]
    names = [("mod", f) for f in files]
    for p, z in paks():
        for n in z.namelist():
            if n.lower().startswith("scripts/") and n.lower().endswith(".shader"):
                names.append((p, n))
    for src, f in names:
        t = open(f, encoding="latin-1").read() if src == "mod" else None
        if t is None:
            for p, z in paks():
                if p == src:
                    t = z.read(f).decode("latin-1")
                    break
        if t is None:
            continue
        t = re.sub(r"/\*.*?\*/", " ", t, flags=re.S)
        t = "\n".join(l.split("//")[0] for l in t.splitlines())
        for name, body in _blocks(t):
            out.setdefault(name.lower(), body)
    return out


_NAME_THEN_BRACE = re.compile(r"^[ \t]*([A-Za-z0-9_\-/\.]+)[ \t]*\r?\n[ \t]*\{", re.M)


def _blocks(t):
    """Yield (name, body) for every top-level shader block, matching braces properly.

    THIS REPLACES A NON-GREEDY REGEX, AND THAT IS THE WHOLE BUG (bug-2225). The old pattern ended the
    body at the FIRST newline-then-brace it could find, which for any shader carrying a stage block is
    the STAGE's closing brace, not the block's. Every captured body therefore swallowed the stage's
    opening brace and dropped its closing one, and the emitter - which wraps the body in its own pair -
    wrote two opens against one close, 70 times over.

    gl2 does not tolerate that the way gl1 does: ScanAndLoadShaderFiles runs a brace pre-check and on
    failure frees the ENTIRE buffer (buffers[i] = NULL), so one malformed block silently removed all 70
    definitions. The only trace was a single WARNING line in qconsole.log.
    """
    i, n = 0, len(t)
    while i < n:
        m = _NAME_THEN_BRACE.search(t, i)
        if not m:
            return
        name = m.group(1)
        open_at = t.index("{", m.end() - 1)
        depth, j = 0, open_at
        while j < n:
            c = t[j]
            if c == "{":
                depth += 1
            elif c == "}":
                depth -= 1
                if depth == 0:
                    break
            j += 1
        if depth != 0:              # unterminated - stop rather than yield a broken body
            return
        yield name, t[open_at + 1:j]
        i = j + 1


# ----------------------------------------------------------------- the composite
def make_blood(base, tier, seed):
    cov, arange, rrange = TIERS[tier]
    w, h = base.size
    rng = random.Random(seed + tier)
    mask = Image.new("L", (w, h), 0)
    d = ImageDraw.Draw(mask)

    # area-driven blob count, so coverage is resolution independent
    rmin, rmax = rrange[0] * w, rrange[1] * w
    avg_area = math.pi * ((rmin + rmax) / 2.0) ** 2
    n = max(1, int((cov * w * h) / (avg_area * 0.55)))
    for _ in range(n):
        cx, cy = rng.uniform(0, w), rng.uniform(0, h)
        r = rng.uniform(rmin, rmax)
        a = int(255 * rng.uniform(*arange))
        # irregular: a few overlapping lobes rather than a disc
        for _l in range(rng.randint(2, 4)):
            ox, oy = rng.uniform(-r * 0.6, r * 0.6), rng.uniform(-r * 0.6, r * 0.6)
            rr = r * rng.uniform(0.45, 1.0)
            d.ellipse([cx + ox - rr, cy + oy - rr, cx + ox + rr, cy + oy + rr], fill=a)
    mask = mask.filter(ImageFilter.GaussianBlur(radius=max(1.0, w / 220.0)))

    # run-off streaks: blood moves down the UV, which reads as gravity on most character maps
    if tier != "_blood1":
        streak = mask.filter(ImageFilter.GaussianBlur(radius=max(1.0, w / 500.0)))
        sp = streak.load()
        mp = mask.load()
        drop = int(h * (0.05 if tier == "_blood2" else 0.09))
        for y in range(h - 1, drop, -1):
            for x in range(0, w, 2):
                v = sp[x, y - drop]
                if v > 90 and mp[x, y] < v:
                    mp[x, y] = int(v * 0.55)
        mask = mask.filter(ImageFilter.GaussianBlur(radius=max(1.0, w / 400.0)))

    fresh = Image.new("RGB", (w, h), FRESH)
    dried = Image.new("RGB", (w, h), DRIED)
    blood = Image.blend(dried, fresh, 0.65 if tier == "_blood3" else 0.85)
    return Image.composite(blood, base, mask)


# ----------------------------------------------------------------- driver
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--targets", required=True, help="file listing tiki paths to cover")
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--list", action="store_true")
    args = ap.parse_args()
    if not (args.write or args.check):
        args.list = True

    tiks = [l.strip() for l in open(args.targets, encoding="utf-8") if l.strip() and not l.startswith("#")]
    SH = shader_bodies()

    # collect the base shaders that need variants
    need = {}
    for t in tiks:
        body = read_text(t)
        if body is None:
            continue
        body = re.sub(r"/\*.*?\*/", " ", body, flags=re.S)
        body = "\n".join(l.split("//")[0] for l in body.splitlines())
        seen = set()
        for m in re.finditer(r"^\s*surface\s+(\S+)\s+shader\s+(\S+)", body, re.I | re.M):
            surf, sh = m.group(1).lower(), m.group(2).lower()
            if SURF_SKIP.search(surf) or surf in seen:
                continue
            seen.add(surf)
            if all((sh + tr) in SH for tr in TIERS):
                continue  # already complete
            need.setdefault(sh, []).append(t)

    print("  base shaders needing variants: %d" % len(need))
    made, skipped, drift = 0, 0, 0
    shader_out = []

    for sh in sorted(need):
        body = SH.get(sh)
        if body is None:
            print("    SKIP %-30s (no shader definition)" % sh)
            skipped += 1
            continue
        mm = re.search(r"\bmap\s+(\S+)", body)
        if not mm or mm.group(1).startswith("$"):
            print("    SKIP %-30s (no plain map stage)" % sh)
            skipped += 1
            continue
        tex = mm.group(1)
        got = best_image(tex)
        if got is None:
            print("    SKIP %-30s (base texture not found: %s)" % (sh, tex))
            skipped += 1
            continue
        base, src = got
        stem = re.sub(r"\.(tga|jpg|jpeg|png)$", "", tex, flags=re.I)

        for tier in ("_blood1", "_blood2", "_blood3"):
            name = sh + tier
            if name in SH:
                continue
            outrel = stem + tier + ".jpg"
            outabs = os.path.join(MOD, outrel.replace("/", os.sep))
            img = make_blood(base, tier, sh)
            buf = io.BytesIO()
            img.save(buf, "JPEG", quality=92)
            data = buf.getvalue()

            if args.check:
                if not os.path.exists(outabs) or open(outabs, "rb").read() != data:
                    print("    DRIFT %s" % outrel)
                    drift += 1
                continue
            if args.write:
                os.makedirs(os.path.dirname(outabs), exist_ok=True)
                open(outabs, "wb").write(data)
            made += 1

            # clone the base shader body, retargeted at the new diffuse
            nb = re.sub(re.escape(tex), outrel, body)
            shader_out.append("%s\n{%s\n}\n" % (name, nb))
        if args.list:
            print("    %-30s base=%s %s" % (sh, base.size, src))

    if args.write and shader_out:
        hdr = ("// HZM coop - GORE TIER 1 (damage-tier blood skins), SECOND PASS.\n"
               "// GENERATED by docs/tools/gen_gore_skins.py - do not hand-edit, re-run the generator.\n"
               "// Companion to scripts/coop_gore.shader, whose original generator was lost in a session\n"
               "// scratchpad; this one lives in the repo and has a --check mode so that cannot recur.\n"
               "// Each block is the model's ORIGINAL surface shader body, retargeted at a composited\n"
               "// diffuse whose blood pixels are the mod's authority colours #150200 fresh / (7,1,0)\n"
               "// dried. Coverage and alpha are matched to the already-shipped skins by measurement.\n\n")
        text = hdr + "\n".join(shader_out)
        _assert_balanced(shader_out)
        _assert_parseable(text)
        _assert_not_shrinking(len(shader_out))
        with open(OUT_SHADER, "w", encoding="latin-1", newline="\n") as fh:
            fh.write(text)
        print("  wrote %s (%d shader blocks)" % (os.path.relpath(OUT_SHADER, REPO), len(shader_out)))

    print("  %s: %d texture(s), %d skipped, %d drift"
          % ("CHECK" if args.check else ("WROTE" if args.write else "DRY RUN"), made, skipped, drift))
    return 1 if (args.check and drift) else 0


if __name__ == "__main__":
    sys.exit(main())
