#!/usr/bin/env python3
"""
Emit ubersound/coop_paintiers.scr - the SEVERITY-TIERED player pain pool.

WHY THIS EXISTS
    Player::Pain() ends in an unconditional Sound("player_pain") (player.cpp:3736/3739) and the
    engine resolves that by PREFIX (Alias_ListFindRandomRange), drawing UNIFORMLY across the pool.
    So a 5-damage graze and a near-fatal hit produce the identical sound. The 24 real takes make
    that worse: they are one actor, all peak-normalised to -0.0 dBFS, so they are the same loudness
    as well as the same intensity.

WHY NOT "SORT THE TAKES INTO TIERS"
    That was the earlier plan and it was wrong. The takes are IMA-ADPCM and of roughly equal
    intensity, so any sort would be arbitrary AND would cut each tier's variety to a third. You do
    not need to sort them - you need to PLAY them differently. volume and pitch are per-alias in
    soundparms, so every tier gets ALL the takes, rendered differently.

NAMING - PREFIX COLLISION IS THE TRAP HERE
    Sound() matches by prefix, so "player_painlt01" would ALSO be matched by Sound("player_pain")
    and would quadruple the base pool for any caller still using it. The tier prefixes therefore do
    NOT start with player_pain, and no tier name is a prefix of another tier name. A bare
    "coop_hurt" alias is deliberately NEVER defined, so nothing can accidentally draw across tiers.

ALIAS FLAGS
    `aliascache ... always maps "..."` is copied verbatim from coop_pain.scr, and both halves matter:
    bLoadForMap on an EMPTY maps buffer returns FALSE, so a maps-less alias loads NOWHERE; `always`
    reaches GlobalAlias_Add unconditionally so the NAME resolves on any map, while the maps list is
    what actually drives CacheResource, which is gated separately.
"""
import io, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MOD  = os.path.join(ROOT, '..', 'hzm-mohaa-coop-mod')
SRC  = os.path.normpath(os.path.join(MOD, 'ubersound', 'coop_pain.scr'))
OUT  = os.path.normpath(os.path.join(MOD, 'ubersound', 'coop_paintiers.scr'))

MAPS = 'always maps "m e t dm obj lib train"'

# name, volume, volMod, pitch, pitchMod, minDist, maxDist
#   light  quieter and HIGHER - a graze, a yelp
#   med    the retail baseline, unchanged, so "normal" still sounds like it always did
#   heavy  louder, LOWER and less pitch-scatter - a grave, committed cry that also carries further
TIERS = [
    ('coop_hurtlt', 0.85, 0.10, 1.10, 0.08, 400, 1400),
    ('coop_hurtmd', 1.15, 0.10, 0.98, 0.10, 400, 1800),
    ('coop_hurthv', 1.45, 0.08, 0.86, 0.06, 500, 2400),
]

def main():
    txt = io.open(SRC, encoding='utf-8', errors='replace').read().replace('\r\n', '\n')
    wavs, seen = [], set()
    for m in re.finditer(r'^aliascache\s+player_pain\S*\s+(\S+\.wav)', txt, re.M):
        w = m.group(1)
        if w.lower().endswith('null.wav'):
            continue
        if w not in seen:
            seen.add(w); wavs.append(w)
    if not wavs:
        print('FAIL: no real takes found in %s' % SRC); return 1

    # names must not collide by prefix, in either direction
    for a in TIERS:
        for b in TIERS:
            if a[0] != b[0] and (a[0].startswith(b[0]) or b[0].startswith(a[0])):
                print('FAIL: prefix collision %s / %s' % (a[0], b[0])); return 1
        if a[0].startswith('player_pain'):
            print('FAIL: %s would be matched by Sound("player_pain")' % a[0]); return 1

    L = []
    L.append('// HZM coop - SEVERITY-TIERED PLAYER PAIN. GENERATED by docs/tools/gen_pain_tiers.py.')
    L.append('// DO NOT EDIT BY HAND - re-run the generator; it reads the take list out of coop_pain.scr')
    L.append('// so the tiers can never drift from the pool they are built on.')
    L.append('//')
    L.append('// Every tier carries ALL %d takes, rendered at a different volume and pitch. The takes are' % len(wavs))
    L.append('// one actor, all peak-normalised, so they cannot be SORTED by intensity - but they can be')
    L.append('// PLAYED differently, and that is what makes a graze and a mortal hit sound different.')
    L.append('//')
    L.append('// Prefixes deliberately do NOT begin with player_pain: Sound() matches by PREFIX, so such a')
    L.append('// name would also be drawn by Sound("player_pain") and would pollute the base pool. No bare')
    L.append('// "coop_hurt" alias is defined either, so nothing can draw ACROSS tiers.')
    L.append('//')
    L.append('// Selected by Player::Pain from the damage it already has in scope; thresholds are')
    L.append('// coop_painTierLo / coop_painTierHi, as a PERCENT of max_health so they follow coop_health.')
    L.append('')
    for name, vol, vmod, pit, pmod, mn, mx in TIERS:
        L.append('// ---- %s ----' % name)
        for i, w in enumerate(wavs, 1):
            L.append('aliascache %s%02d %s soundparms %.2f %.2f %.2f %.2f %d %d voice loaded %s'
                     % (name, i, w, vol, vmod, pit, pmod, mn, mx, MAPS))
        L.append('')
    io.open(OUT, 'w', encoding='utf-8', newline='\n').write('\n'.join(L))
    print('  %d takes x %d tiers = %d aliases -> %s'
          % (len(wavs), len(TIERS), len(wavs)*len(TIERS), os.path.relpath(OUT, ROOT)))
    return 0

if __name__ == '__main__':
    sys.exit(main())
