#!/usr/bin/env python
"""Generate coop_mod/mp_baseassault_maps.scr - the authored MP Base Assault layouts for the five
single-player campaign maps that UberMod's Base Assault shipped on (m1l3a, m1l3b, m4l1, m5l2a, m5l3).

WHY THIS EXISTS
    Those SP bsps carry ZERO multiplayer team spawns (one info_player_start each), so MP Base Assault
    cannot place players on them, and it derives base positions from real spawn origins (which never
    arrive). The OwN-3m-All UberMod V5 "Base Assault" (by ViPER / own3malls) solved this by SCRIPT-
    SPAWNING ordered team spawn groups AND hand-placing the destructible bases per map. Coordinates were
    harvested from that mod (base_assault/maps/<map>.scr for spawns; global/BAS/map.scr::spawn_bases for
    the base positions) into docs/tools/baseassault_maps.json. Credit: OwN-3m-All / ViPER.

    This emits, per map, a seed thread that spawns all the info_player_allied/axis entities (so the stock
    MP spawn-selection has team spawns to pick from) and records the authored base positions + yaws into
    level.coop_mpBaSeed[side][idx] / level.coop_mpBaYaw[side][idx] with per-side counts. coop_mod/
    mp_baseassault.scr::bas_seedAuthored reads those and builds the real bases, in place of the derive-
    from-spawn-origins path. No bsp is touched; nothing here runs on a coop map (coop_mpRun-guarded).

    python docs/tools/gen_baseassault_maps.py check   # regenerate in memory + byte-compare (exit 1 = drift)
    python docs/tools/gen_baseassault_maps.py build   # write the file

ISOLATION
    Output is coop_mod/mp_baseassault_maps.scr - an MP file (coop_mod/mp*.scr is in MP_MANIFEST), coop_mpRun-
    guarded, naming only coop_mpBa* level vars (MP-owned) and stock spawn builtins. Angles/yaws are
    normalised to [0,360) so no bare-negative scalar assignment appears (only vector literals carry
    negatives, which are valid). ASCII, LF, no BOM.
"""
import io
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
MOD = os.path.join(ROOT, "hzm-mohaa-coop-mod")
DATA = os.path.join(os.path.dirname(os.path.abspath(__file__)), "baseassault_maps.json")
OUT = os.path.join(MOD, "coop_mod", "mp_baseassault_maps.scr")

ORDER = ["m1l3a", "m1l3b", "m4l1", "m5l2a", "m5l3"]


def norm_ang(a):
    a = int(round(a)) % 360
    if a < 0:
        a += 360
    return a


def fnum(v):
    r = round(v, 1)
    if r == int(r):
        return str(int(r))
    return ("%.1f" % r)


def load():
    return json.load(io.open(DATA, encoding="utf-8"))


def seed_thread(mapname, rec):
    spawns = rec["spawns"]
    bases = rec["bases"]
    L = ["seed_%s:" % mapname, "{"]
    # spawn every authored team spawn point (stock team spawn entities for MP spawn-selection)
    for s in spawns:
        cls = "info_player_allied" if s["side"] == "a" else "info_player_axis"
        L.append('\tlocal.e = spawn %s' % cls)
        L.append('\tlocal.e.origin = ( %s %s %s )' % (fnum(s["x"]), fnum(s["y"]), fnum(s["z"])))
        L.append('\tlocal.e.angle = %d' % norm_ang(s["ang"]))
    # authored destructible bases, per side, in listed order
    idx = {"a": 0, "x": 0}
    for b in bases:
        side = b["side"]
        idx[side] += 1
        i = idx[side]
        L.append('\tlevel.coop_mpBaSeed["%s"][%d] = ( %s %s %s )' % (side, i, fnum(b["x"]), fnum(b["y"]), fnum(b["z"])))
        L.append('\tlevel.coop_mpBaYaw["%s"][%d] = %d' % (side, i, norm_ang(b["yaw"])))
    na, nx = idx["a"], idx["x"]
    L.append('\tlevel.coop_mpBaSeedN["a"] = %d' % na)
    L.append('\tlevel.coop_mpBaSeedN["x"] = %d' % nx)
    L.append('\tlevel.coop_mpBaSeedTotal = %d' % (na + nx))
    L.append('\tprintln( "^~^~^ MPBASMAP seeded %s spawns=%d bases=a%d/x%d" )' % (mapname, len(spawns), na, nx))
    L.append("}end")
    return "\n".join(L)


def render(data):
    present = [m for m in ORDER if m in data]
    L = [
        "//GENERATED by docs/tools/gen_baseassault_maps.py -- DO NOT HAND-EDIT (regenerate instead).",
        "//Authored MP Base Assault layouts for the 5 SP campaign maps UberMod's Base Assault shipped on.",
        "//Coordinates harvested from OwN-3m-All UberMod V5 (Base Assault by ViPER); this is an MP-isolated",
        "//rebuild. The bsps carry no MP team spawns, so we script-spawn them here and hand-place the",
        "//destructible bases; coop_mod/mp_baseassault.scr::bas_seedAuthored consumes coop_mpBaSeed*.",
        "//coop_mpRun-guarded; a compile canary on every MP boot.",
        "alive:{",
        "\tend 1",
        "}end",
        "",
        "//Spawn the authored layout for the current map (lowercased mapname). Sets level.coop_mpBaSeed[side]",
        "//[1..N] (base positions) + coop_mpBaYaw + coop_mpBaSeedN[side], and returns the total base count",
        "//(0 = not an authored map).",
        "seed local.map:{",
        "\tif( level.coop_mpRun != 1 ){ end 0 }",
        '\tlevel.coop_mpBaSeedN["a"] = 0',
        '\tlevel.coop_mpBaSeedN["x"] = 0',
        "\tlevel.coop_mpBaSeedTotal = 0",
        "\tswitch( local.map ){",
    ]
    for m in present:
        L.append('\t\tcase "%s":' % m)
        L.append("\t\t\twaitthread seed_%s" % m)
        L.append("\t\t\tbreak")
    L += [
        "\t}",
        "\tend level.coop_mpBaSeedTotal",
        "}end level.coop_mpBaSeedTotal",
        "",
    ]
    for m in present:
        L.append(seed_thread(m, data[m]))
        L.append("")
    return "\n".join(L).rstrip("\n") + "\n"


def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else "check"
    data = load()
    text = render(data)
    try:
        text.encode("ascii")
    except UnicodeEncodeError:
        raise SystemExit("gen_baseassault_maps: output is not ASCII")
    if mode == "build":
        io.open(OUT, "wb").write(text.encode("ascii"))
        print("wrote %s (%d bytes)" % (os.path.relpath(OUT, ROOT), len(text)))
        return 0
    if not os.path.exists(OUT):
        print("MISSING %s - run: python docs/tools/gen_baseassault_maps.py build" % os.path.relpath(OUT, ROOT))
        return 1
    cur = io.open(OUT, "r", encoding="latin-1", newline="").read()
    if cur == text:
        print("EXACT REPRODUCTION (%s)" % os.path.relpath(OUT, ROOT))
        return 0
    print("DRIFT - run: python docs/tools/gen_baseassault_maps.py build")
    return 1


if __name__ == "__main__":
    sys.exit(main())
