#!/usr/bin/env python3
"""
GLOVE ARMORY UI (bug-2080) - page cfgs + the coop_loadout.urc relayout.

THE LAYOUT PROBLEM, and why this is a relayout rather than "add two more buttons". The armory's
bottom-left corner is boxed in on both sides:

  * ABOVE, the character model viewer occupies rect (12 46 134 348). A rendermodel widget is
    composited AFTER plain 2D widgets regardless of ordernumber, so nothing can be layered over it -
    two attempts at that failed (see the note at coop_loadout.urc:145). Anything readable has to be
    outside the model's box.
  * BELOW, the unlock caption was moved to y444+ for exactly that reason and must not move back up.

That leaves y396..y443 - 47 pixels - which previously held two rows (uniform at 396, helmet at 426)
at 15px each. Three rows fit only if every row shrinks: 14px tall on a 16px pitch, 396 / 412 / 428,
ending at 442 with the caption still clear at 444.

Font stays verdana-12. verdana-10 is NOT an option: the build log shows `LoadFont: Couldn't load
font verdana-10` six times per run, so a smaller font would silently fall back and look wrong.

    python docs/tools/gen_glove_ui.py --write
"""
import io
import os
import re
import sys

MOD = r'C:\mohaa-coop-dev\hzm-mohaa-coop-mod'
URC = os.path.join(MOD, 'ui', 'coop_loadout.urc')
CFG_DIR = os.path.join(MOD, 'ui', 'loadout', 'glove')

# Must match coop_mod/gloves.scr::glove_initList exactly - the index is the contract between them.
GLOVES = [
    (0, 'Bare Hands'),
    (1, 'Leather Gloves'),
    (2, 'Wool Knit Gloves'),
    (3, 'US Winter Gloves'),
    (4, 'Wool Mittens'),
    (5, "Seaman's Gloves"),
    (6, 'Alpine Hands'),
]

# LAYOUT, measured off the background texture rather than guessed (2026-08-23, after the first
# attempt overlapped and the user sent a screenshot):
#
#   * "SKIN" and "HELMET" are NOT widgets - they are PAINTED INTO textures/mohmenu/coop_lo_bg2.tga
#     and cannot be moved. Measured from the .tga: SKIN occupies x15-27 / y384-391 and HELMET
#     x15-36 / y414-421. The first attempt put the helmet buttons at y412, straight through the
#     baked HELMET word, which is exactly what the screenshot showed.
#   * The character model viewer is rect (12 46 134 348) = x12-146, y46-394, and a rendermodel
#     widget composites AFTER 2D widgets regardless of ordernumber (see coop_loadout.urc:145). So
#     nothing interactive may sit above y394 - that is why the original buttons began at y396.
#   * The unlock caption is pinned at y444+ for the same reason and must not move.
#
# That leaves y396..y443. Three 14px rows on a 16px pitch fit, and every widget starts at x76 -
# clear of the baked captions' x15-36 - so the rows sit BESIDE the words instead of on top of them.
# Buttons become single arrows rather than "< PREV" / "NEXT >" so a whole row fits on one line.
ROWS = {'skin': 396, 'helm': 412, 'glove': 428}
H = 14
ARROW_X_PREV = 76
ARROW_X_NEXT = 100
ARROW_W = 20
NAME_X = 126
NAME_W = 210
# GLOVES has no baked caption, so this row supplies its own, styled like the painted ones.
GLOVE_LBL = (14, 58)


def write_cfgs():
    if not os.path.isdir(CFG_DIR):
        os.makedirs(CFG_DIR)
    n = len(GLOVES)
    for i, (idx, name) in enumerate(GLOVES):
        prv = (i - 1) % n
        nxt = (i + 1) % n
        body = (
            '// GENERATED by docs/tools/gen_glove_ui.py - DO NOT HAND-EDIT\n'
            '// Armory glove page %d of %d. Same shape as ui/loadout/helm/hNN.cfg: each page\n'
            '// redefines the prev/next execs and the append token, so a button press is always\n'
            '// "move to a page, then send THAT page\'s token".\n'
            'set coop_loGlove "%d"\n'
            'set coop_loGloveNm "%s"\n'
            'set coop_loGloveP "exec ui/loadout/glove/g%02d.cfg"\n'
            'set coop_loGloveN "exec ui/loadout/glove/g%02d.cfg"\n'
            'set coop_loAGlove "append name ,gn%d"\n'
        ) % (idx, n, idx, name, GLOVES[prv][0], GLOVES[nxt][0], idx)
        io.open(os.path.join(CFG_DIR, 'g%02d.cfg' % idx), 'w',
                encoding='ascii', newline='\n').write(body)
    return n


BUTTON = '''
resource
Button
{
name "%(name)s"
title "%(title)s"
rect %(x)d %(y)d 60 %(h)d
fgcolor 0.85 0.83 0.78 1.00
bgcolor 0.10 0.11 0.14 0.92
borderstyle "3D_BORDER"
font "verdana-12"
clicksound "sound/menu/scroll.wav"
stuffcommand "%(cmd)s"
}
'''

LABEL = '''
resource
Label
{
name "gloveNameLbl"
rect 150 %(y)d 190 %(h)d
fgcolor 0.92 0.86 0.62 1.00
bgcolor 0.00 0.00 0.00 0.00
font "verdana-12"
linkcvar "coop_loGloveNm"
}
'''


def patch_urc(write):
    s = io.open(URC, encoding='utf-8', errors='surrogateescape', newline='').read()
    nl = '\r\n' if '\r\n' in s else '\n'
    orig = s

    def setrect(pattern, x, y, w, h):
        nonlocal s
        rx = re.compile(pattern, re.S)
        m = rx.search(s)
        if not m:
            raise AssertionError('rect anchor not found: ' + pattern[:60])
        s = s[:m.start(1)] + ('rect %d %d %d %d' % (x, y, w, h)) + s[m.end(1):]

    # uniform row -> y396, helmet row -> y412 (was 426 / label 416)
    setrect(r'name "skinPrev".*?(rect \d+ \d+ \d+ \d+)', 14, ROWS['skin'], 60, H)
    setrect(r'name "skinNext".*?(rect \d+ \d+ \d+ \d+)', 84, ROWS['skin'], 60, H)
    setrect(r'name "skinNameLbl".*?(rect \d+ \d+ \d+ \d+)', 150, ROWS['skin'], 190, H)
    setrect(r'name "helmPrev".*?(rect \d+ \d+ \d+ \d+)', 14, ROWS['helm'], 60, H)
    setrect(r'name "helmNext".*?(rect \d+ \d+ \d+ \d+)', 84, ROWS['helm'], 60, H)
    setrect(r'name "helmNameLbl".*?(rect \d+ \d+ \d+ \d+)', 150, ROWS['helm'], 190, H)

    if 'name "glovePrev"' not in s:
        block = (
            nl
            + '// [user 2026-08-23, bug-2080] GLOVES row. The uniform and helmet rows above were'
            + nl + '// shrunk from 15px to 14px and repitched to 396/412/428 to make room, because the'
            + nl + '// caption below at y444 cannot move (it was put there to escape the model viewer,'
            + nl + '// which composites over any 2D widget regardless of ordernumber - see :145).'
            + nl
            + (BUTTON % {'name': 'glovePrev', 'title': '< PREV', 'x': 14, 'y': ROWS['glove'],
                         'h': H, 'cmd': 'vstr coop_loGloveP ; vstr coop_loAGlove'}).replace('\n', nl)
            + (BUTTON % {'name': 'gloveNext', 'title': 'NEXT >', 'x': 84, 'y': ROWS['glove'],
                         'h': H, 'cmd': 'vstr coop_loGloveN ; vstr coop_loAGlove'}).replace('\n', nl)
            + (LABEL % {'y': ROWS['glove'], 'h': H}).replace('\n', nl)
        )
        anchor = 'name "helmNext"'
        i = s.find(anchor)
        j = s.find('}', s.find('stuffcommand', i))
        s = s[:j + 1] + block + s[j + 1:]

    if write:
        io.open(URC, 'w', encoding='utf-8', errors='surrogateescape', newline='').write(s)
    return s != orig


def main():
    write = '--write' in sys.argv
    n = write_cfgs() if write else len(GLOVES)
    changed = patch_urc(write)
    print('GLOVE ARMORY UI  (%s)' % ('WROTE' if write else 'dry run'))
    print('  page cfgs           : %d  -> ui/loadout/glove/gNN.cfg' % n)
    print('  rows repitched      : uniform y%d, helmet y%d, gloves y%d (14px, was 15px)'
          % (ROWS['skin'], ROWS['helm'], ROWS['glove']))
    print('  bottom of glove row : y%d   (unlock caption still clear at y444)'
          % (ROWS['glove'] + H))
    print('  urc changed         : %s' % changed)
    return 0


if __name__ == '__main__':
    sys.exit(main())
