#!/usr/bin/env python3
"""Generate coop_mod/mp_countdown_maps.scr from countdown_radios.tsv.

The Countdown mode (imported htr/ engine) spawns a "radio" at one of a map's authored candidate origins.
Those origins were harvested from the upstream countdown mod's per-map scripts (countdown/<map>.scr). This
emits radioOriginsFor(map) - returning the origin array for the current (path-stripped, lowercased) mapname,
or NIL when the map has no data - which the loader feeds to htr/setup.scr in place of its own
`exec countdown/<map>.scr` lookup.

Run:  python docs/tools/gen_countdown_maps.py         (write)
      python docs/tools/gen_countdown_maps.py check   (exit 1 if the .scr is stale)
"""
import sys, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TSV = os.path.join(ROOT, "docs", "tools", "countdown_radios.tsv")
OUT = os.path.join(ROOT, "hzm-mohaa-coop-mod", "htr", "countdown_maps.scr")


def norm_origin(o):
    """Normalize a harvested vector literal to `( x y z )` with real spacing. The upstream data has
    inconsistent forms like `(-855.95 628.68 -1614.23 )` and `(1037.74 ...)` - an open paren immediately
    followed by a number/minus reads as the `(-1)` bare-negative-in-parens PARSE KILLER (a space after `(`
    is what makes it a vector literal). Re-emit from the three parsed numbers so every origin is valid."""
    nums = re.findall(r'-?\d+(?:\.\d+)?', o)
    if len(nums) != 3:
        raise ValueError("bad origin (need 3 numbers): %r" % o)
    return "( %s %s %s )" % (nums[0], nums[1], nums[2])


def load():
    data = {}
    for line in open(TSV, encoding="latin-1"):
        line = line.rstrip("\n")
        if not line or line.startswith("#"):
            continue
        m, origin = line.split("\t", 1)
        data.setdefault(m, []).append(norm_origin(origin.strip()))
    return data


def build():
    data = load()
    L = []
    L.append("// GENERATED by docs/tools/gen_countdown_maps.py from countdown_radios.tsv. Do NOT hand-edit.")
    L.append("// Per-map Countdown radio spawn origins, harvested from the upstream countdown mod. coop_mod/")
    L.append("// mp_countdown.scr LOADS the real htr/ radio engine and feeds it these origins via radioOriginsFor")
    L.append("// (called from htr/setup.scr::getorigin). MP-only (gated by the countdown mode which needs")
    L.append("// level.coop_mpRun); never touches coop.")
    L.append("")
    L.append("//return the candidate radio-spawn origins for a map (path-stripped, lowercased mapname), or NIL.")
    L.append("radioOriginsFor local.map:{")
    L.append("\tlocal.o = NIL")
    for m in sorted(data):
        L.append('\tif( local.map == "%s" ){' % m)
        for i, o in enumerate(data[m]):
            L.append("\t\tlocal.o[%d] = %s" % (i, o))
        L.append("\t}")
    L.append("}end local.o")
    L.append("")
    return "\n".join(L)


def main():
    text = build()
    if len(sys.argv) > 1 and sys.argv[1] == "check":
        cur = open(OUT, encoding="latin-1").read() if os.path.exists(OUT) else ""
        if cur != text:
            print("STALE: mp_countdown_maps.scr differs from generator output")
            sys.exit(1)
        print("OK: mp_countdown_maps.scr matches generator")
        return
    open(OUT, "w", encoding="latin-1", newline="\n").write(text)
    data = load()
    print("wrote %s (%d maps, %d origins)" % (os.path.relpath(OUT, ROOT), len(data), sum(len(v) for v in data.values())))


if __name__ == "__main__":
    main()
