#!/usr/bin/env python
"""gen_flvo_pools.py -> ubersound/coop_flvo.scr + ubersound/coop_taunt.scr

[user 2026-10-05] "random radio-like dialogue about staying in position and a tank ... like dialogue
from the campaign somewhere at random, doesn't belong on that map."

The Frontline battle-chatter and MP-taunt pools used to be hand-written alias lists whose curation
nobody could check (the manifest they cited was not in the repo). They are now GENERATED from one
curated table, docs/tools/vo_curation.tsv, built from whisper transcripts of every take
(docs/proposals/chatter_prune_2026-10-05/manifest.tsv is the full audit it came from).

vo_curation.tsv columns: pool  file  transcript  translation  verdict  reason
  pool     flvo_de | flvo_us | taunt_de | taunt_us
  file     sound path as the alias references it
  verdict  KEEP          generic combat bark: goes in the random pool flchatter.scr rolls during
                         active combat (coop_flvo_de / coop_flvo_us / coop_taunt_de / coop_taunt_us)
           KEEP+<sit>    the same, AND also a take of the aivoice situation <sit>
           MOVE:<sit>    situation-only: NOT in the random pool (it would play when the situation is
                         not happening), only in the aivoice pool coop_av_<nat>_<sit>
           CUT           never aliased (story / orders / vehicles / alerts with no trigger / garbled)

NAMES. flchatter.scr plays the BARE pool name ("coop_flvo_de"); the engine resolves it by PREFIX
(Alias_ListFindRandomRange) and draws uniformly over every member, so there is no pool size to keep in
sync. Members are zero-padded (coop_flvo_de01..) - the old coop_flvo_de1 also matched de10..de19, so a
"random 1..90" pick was really a pick among 11 for every single-digit index.
Situation takes are named coop_av_<nat>_<sit>fl<NN>: the 'f' sorts after the digit-numbered retail
members of the same pool (coop_aivoice.scr / coop_chatter.scr, renumbered by fix_vo_pools.py), keeps
them contiguous with them, and can never collide with fix_vo_pools' own numbering.

Rerunnable; output is generated - do not hand-edit coop_flvo.scr / coop_taunt.scr.
"""
import csv, io, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
MOD = os.path.normpath(os.path.join(HERE, "..", "..", "hzm-mohaa-coop-mod"))
TABLE = os.path.join(HERE, "vo_curation.tsv")

FLVO_PARMS = 'soundparms 1.0 0.1 1.0 0.05 320 2600 auto loaded maps "m e t dm obj train"'
# situation takes mirror the parms of the coop_aivoice.scr pool they join, so the mix stays level
SIT_PARMS = {
    "attack":   'soundparms 1.15 0.10 1.0 0.05 200 2000 dialog loaded maps "m e t dm obj train"',
    "taunt":    'soundparms 1.10 0.10 1.0 0.05 180 1800 dialog loaded maps "m e t dm obj train"',
    "kill":     'soundparms 1.10 0.10 1.0 0.05 180 1800 dialog loaded maps "m e t dm obj train"',
    "cover":    'soundparms 1.15 0.10 1.0 0.05 200 2000 dialog loaded maps "m e t dm obj train"',
    "backup":   'soundparms 1.15 0.10 1.0 0.05 200 2000 dialog loaded maps "m e t dm obj train"',
    "fallback": 'soundparms 1.15 0.10 1.0 0.05 200 2000 dialog loaded maps "m e t dm obj train"',
    "mandown":  'soundparms 1.15 0.10 1.0 0.05 200 2000 dialog loaded maps "m e t dm obj train"',
    "contact":  'soundparms 1.15 0.10 1.0 0.05 220 2400 dialog loaded maps "m e t dm obj train"',
}
POOL_NAME = {"flvo_de": "coop_flvo_de", "flvo_us": "coop_flvo_us",
             "taunt_de": "coop_taunt_de", "taunt_us": "coop_taunt_us"}
NAT = {"flvo_de": "de", "flvo_us": "us", "taunt_de": "de", "taunt_us": "us"}


def load():
    rows = []
    with io.open(TABLE, encoding="utf-8") as f:
        for r in csv.DictReader(f, delimiter="\t"):
            rows.append(r)
    return rows


def build():
    rows = load()
    gen = {k: [] for k in POOL_NAME}
    sit = {}
    for r in rows:
        v = r["verdict"].strip()
        if v == "CUT":
            continue
        pool = r["pool"].strip()
        if v == "KEEP" or v.startswith("KEEP+"):
            gen[pool].append(r)
        m = re.match(r"(?:KEEP\+|MOVE:)(\w+)$", v)
        if m:
            s = m.group(1)
            if s not in SIT_PARMS:
                sys.exit("unknown situation %r for %s" % (s, r["file"]))
            sit.setdefault((NAT[pool], s), [])
            if r["file"] not in [x["file"] for x in sit[(NAT[pool], s)]]:
                sit[(NAT[pool], s)].append(r)

    def line(name, r, parms):
        sub = r.get("translation") or r.get("transcript") or ""
        return "aliascache %s %s %s" % (name, r["file"], parms) + ("  // " + sub if sub else "")

    out = {}
    L = ["// GENERATED by docs/tools/gen_flvo_pools.py from docs/tools/vo_curation.tsv - DO NOT EDIT.",
         "// HZM coop - MOH Frontline battle chatter (user-approved VO expansion 2026-07-13; re-curated",
         "// 2026-10-05 from whisper transcripts of every take, see the generator header).",
         "// coop_flvo_de / coop_flvo_us = the random combat-bark pools flchatter.scr rolls (bare-name",
         "// prefix pick). coop_av_<nat>_<sit>flNN = situation takes that join coop_mod/aivoice.scr's pools.",
         ""]
    for pool in ("flvo_de", "flvo_us"):
        L.append("// %s - %d takes (random combat pool)" % (POOL_NAME[pool], len(gen[pool])))
        for i, r in enumerate(gen[pool], 1):
            L.append(line("%s%02d" % (POOL_NAME[pool], i), r, FLVO_PARMS))
        L.append("")
    for (nat, s) in sorted(sit):
        takes = sit[(nat, s)]
        L.append("// coop_av_%s_%s - %d Frontline takes (aivoice situation '%s')" % (nat, s, len(takes), s))
        for i, r in enumerate(takes, 1):
            L.append(line("coop_av_%s_%sfl%02d" % (nat, s, i), r, SIT_PARMS[s]))
        L.append("")
    out["coop_flvo.scr"] = L

    T = ["// GENERATED by docs/tools/gen_flvo_pools.py from docs/tools/vo_curation.tsv - DO NOT EDIT.",
         "// HZM coop - MP TAUNT pools so campaign AI can jeer (bug-775 rebuilt 2026-07-18; re-curated",
         "// 2026-10-05: every take transcribed, voice letters checked - AMdfr 'z' is the SAS/BRITISH MP",
         "// voice (uberdialog allied_sas_aa), so it is not an American taunt).",
         "// Rolled by coop_mod/flchatter.scr with the BARE pool name (prefix pick, no size to sync).",
         ""]
    for pool in ("taunt_de", "taunt_us"):
        T.append("// %s - %d takes" % (POOL_NAME[pool], len(gen[pool])))
        for i, r in enumerate(gen[pool], 1):
            T.append(line("%s%02d" % (POOL_NAME[pool], i), r, FLVO_PARMS))
        T.append("")
    out["coop_taunt.scr"] = T
    return out, gen, sit


def main():
    check = "--check" in sys.argv or "check" in sys.argv
    out, gen, sit = build()
    stale = 0
    for fn, L in out.items():
        data = ("\r\n".join(L) + "\r\n").encode("latin-1", errors="replace")
        p = os.path.join(MOD, "ubersound", fn)
        old = open(p, "rb").read() if os.path.exists(p) else b""
        if old != data:
            stale += 1
            if check:
                print("STALE", fn)
            else:
                open(p, "wb").write(data)
                print("wrote", fn)
    for k, v in gen.items():
        print("  %-9s random pool %3d" % (k, len(v)))
    for k in sorted(sit):
        print("  coop_av_%s_%s  +%d situation takes" % (k[0], k[1], len(sit[k])))
    if check and stale:
        sys.exit(1)


if __name__ == "__main__":
    main()
