#!/usr/bin/env python3
"""Generate coop_mod/mp_cybersnd_stations.scr from cybersnd_sites.tsv.

The bomb-site data was harvested from the real UberMod v8 map scripts: each Cyber Attack /
Search & Destroy map sets a few level.* tuning vars, places bomb sites via
`ubermode/cybersnd.scr::bombsite` and the bomb via `::bomb`, then execs the shared mode
(ubermode/cybersnd.scr::main). This emits the dispatch labels the MP loaders call - cs_eligibleFor
(is this map playable in this mode?) and cs_setupFor (replay the map's real setup + placements) -
so the buildabase-style loaders LOAD the real mode rather than reimplementing it.

Run:  python docs/tools/gen_cybersnd_maps.py         (write)
      python docs/tools/gen_cybersnd_maps.py check   (exit 1 if the .scr is stale)
"""
import sys, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TSV = os.path.join(ROOT, "docs", "tools", "cybersnd_sites.tsv")
OUT = os.path.join(ROOT, "hzm-mohaa-coop-mod", "coop_mod", "mp_cybersnd_stations.scr")


def rkey(m):
    """Runtime mapname key. The mohdm* deathmatch maps live in maps/DM/, so the engine's `mapname`
    cvar is "dm/mohdm1" (see mp_koth.scr); the SP campaign maps live in maps/ root, so theirs is bare."""
    return "dm/" + m if re.match(r"^mohdm\d", m) else m


def load():
    """Return {map: {mode: [(kind, payload), ...]}} for cyb/snd modes with bomb data."""
    data = {}
    for line in open(TSV, encoding="latin-1"):
        line = line.rstrip("\n")
        if not line or line.startswith("#"):
            continue
        m, mode, kind, payload = line.split("\t", 3)
        data.setdefault(m, {}).setdefault(mode, []).append((kind, payload))
    return data


def emit_mode_switch(L, data, mode):
    """Emit the per-map switch body for one mode (cyb or snd)."""
    L.append("\tswitch( local.map ){")
    for m in sorted(data):
        rows = data[m].get(mode)
        if not rows:
            continue
        L.append('\tcase "%s":' % rkey(m))
        for kind, payload in rows:
            if kind == "set":
                L.append("\t\tlevel.%s" % payload)
            elif kind == "bombsite":
                L.append("\t\twaitthread ubermode/cybersnd.scr::bombsite %s" % payload)
            elif kind == "bomb":
                L.append("\t\tthread ubermode/cybersnd.scr::bomb %s" % payload)
        L.append("\t\tbreak")
    L.append("\t}")


def build():
    data = load()
    L = []
    L.append("// GENERATED by docs/tools/gen_cybersnd_maps.py from cybersnd_sites.tsv. Do NOT hand-edit.")
    L.append("// Per-map Cyber Attack / Search & Destroy bomb data, harvested verbatim from the real UberMod")
    L.append("// v8.00 map scripts. coop_mod/mp_snd.scr and coop_mod/mp_cyberattack.scr LOAD the real mode")
    L.append("// (ubermode/cybersnd.scr): they call cs_eligibleFor to gate a map, then cs_setupFor to replay")
    L.append("// that map's real tuning + bomb-site/bomb placements before exec'ing the shared mode's ::main.")
    L.append("// MP-only (coop_mod/mp*.scr, gated by the snd/cyberattack modes which need level.coop_mpRun); never touches coop.")
    L.append("")
    # cs_eligibleFor: 1 if the (map, mode) has real bomb data, else 0.
    L.append("//return 1 if the map is playable in this mode (cyb/snd), else 0.")
    L.append("cs_eligibleFor local.map local.mode:{")
    L.append("\tlocal.e = 0")
    for mode in ("cyb", "snd"):
        maps = [m for m in sorted(data) if data[m].get(mode)]
        L.append('\tif( local.mode == "%s" ){' % mode)
        for m in maps:
            L.append('\t\tif( local.map == "%s" ){ local.e = 1 }' % rkey(m))
        L.append("\t}")
    L.append("}end local.e")
    L.append("")
    L.append("")
    # cs_setupFor: dispatch to the per-mode setup replay.
    L.append("//replay a map's real tuning + bomb placements for the given mode (before exec'ing ::main).")
    L.append("cs_setupFor local.map local.mode:{")
    L.append('\tif( local.mode == "cyb" ){ waitthread cs_setupCyb local.map }')
    L.append('\tif( local.mode == "snd" ){ waitthread cs_setupSnd local.map }')
    L.append("}end")
    L.append("")
    L.append("")
    L.append("cs_setupCyb local.map:{")
    emit_mode_switch(L, data, "cyb")
    L.append("}end")
    L.append("")
    L.append("")
    L.append("cs_setupSnd local.map:{")
    emit_mode_switch(L, data, "snd")
    L.append("}end")
    L.append("")
    return "\n".join(L)


def main():
    text = build()
    if len(sys.argv) > 1 and sys.argv[1] == "check":
        cur = open(OUT, encoding="latin-1").read() if os.path.exists(OUT) else ""
        if cur != text:
            print("STALE: mp_cybersnd_stations.scr differs from generator output")
            sys.exit(1)
        print("OK: mp_cybersnd_stations.scr matches generator")
        return
    open(OUT, "w", encoding="latin-1", newline="\n").write(text)
    data = load()
    ncyb = sum(1 for m in data if data[m].get("cyb"))
    nsnd = sum(1 for m in data if data[m].get("snd"))
    print("wrote %s (cyb:%d maps, snd:%d maps)" % (os.path.relpath(OUT, ROOT), ncyb, nsnd))


if __name__ == "__main__":
    main()
