#!/usr/bin/env python
"""gen_skinbase.py - variant/finish tik -> base give reverse map.

Parses the FORWARD table (coop_mod/loadoutskins.scr, level.coop_skinGive["<give>"][fid] =
"<variant>") and emits coop_mod/loadoutskins_base.scr with the reverse mapping. Consumers
(itemhandler.scr::getAmmoType) use it to classify a finished/variant gun as its BASE - the
ammo-type switch and the primary-class list know only base tiks (apply-trace F2: a finished
primary that lost the engine's second-primary pickup race was silently never re-issued).

Keys are lowercased because the consumer's input has been through makeWeaponStringValid
(which lowercases). Runs on every build (build.ps1), so it can never drift from the table.
"""
import re, io, os, sys

ROOT = os.path.join(os.path.dirname(__file__), "..", "..")
SRC  = os.path.join(ROOT, "hzm-mohaa-coop-mod", "coop_mod", "loadoutskins.scr")
OUT  = os.path.join(ROOT, "hzm-mohaa-coop-mod", "coop_mod", "loadoutskins_base.scr")

src = io.open(SRC, encoding="latin-1").read()
pairs = []
seen = set()
for m in re.finditer(r'level\.coop_skinGive\["([^"]+)"\]\[\d+\]\s*=\s*"([^"]+)"', src):
    give, variant = m.group(1).lower(), m.group(2).lower()
    if variant == give or variant in seen:
        continue
    seen.add(variant)
    pairs.append((variant, give))

nl = "\r\n"
out = ["//GENERATED by docs/tools/gen_skinbase.py from loadoutskins.scr - DO NOT EDIT.",
       "//Reverse map: finished/variant tik -> its base give. Keys lowercased (consumers",
       "//run input through makeWeaponStringValid first).",
       "main:{",
       "\tif( level.coop_skinBaseInit == 1 ){ end }",
       "\tlevel.coop_skinBaseInit = 1"]
for variant, give in pairs:
    out.append('\tlevel.coop_skinBase["%s"] = "%s"' % (variant, give))
out.append("}end")
io.open(OUT, "wb").write((nl.join(out) + nl).encode("latin-1"))
print("loadoutskins_base.scr: %d variant->base entries" % len(pairs))
