#!/usr/bin/env python
"""Generate coop_mod/mp_vehicle_maps.scr - the authored MP vehicle/emplacement placements for the five
SP campaign maps UberMod V5 shipped drivable tanks / jeeps / usable nebelwerfers / flak88 / anti-tank
pickups on (m1l3a, m1l3b, m4l1, m5l2a, m5l3 - the same force-arena maps as Base Assault / Push).

WHY THIS EXISTS
    MP maps ship NO vehicle entities, so the vehicle framework has nothing to place. UberMod authored the
    exact spawn coordinates per map in base_assault/maps/<map>.scr (spawn_tank / spawn_jeep /
    spawn_nebelwerfer / spawn_flak / panceltorok). Those were harvested into docs/tools/
    vehicle_placements.json. This emits, per map, a seed thread that calls coop_mod/mp_vehicles.scr's
    spawner labels with those coordinates. Credit: OwN-3m-All / ViPER.

    python docs/tools/gen_vehicle_maps.py check   # regenerate in memory + byte-compare (exit 1 = drift)
    python docs/tools/gen_vehicle_maps.py build   # write the file

ISOLATION
    Output is coop_mod/mp_vehicle_maps.scr - an MP file (coop_mod/mp*.scr is in MP_MANIFEST), coop_mpRun-
    guarded, naming only coop_mpVeh* level vars (MP-owned) and the mp_vehicles.scr spawner labels (MP->MP,
    clause 10). Angles/yaws are normalised to [0,360) so no bare-negative scalar appears (UberMod had a few
    like -295 / -305 that would be script parse killers). Origins are emitted as vector literals (negatives
    valid there). ASCII, LF, no BOM.
"""
import io
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
MOD = os.path.join(ROOT, "hzm-mohaa-coop-mod")
DATA = os.path.join(os.path.dirname(os.path.abspath(__file__)), "vehicle_placements.json")
OUT = os.path.join(MOD, "coop_mod", "mp_vehicle_maps.scr")

ORDER = ["m1l3a", "m1l3b", "m4l1", "m5l2a", "m5l3"]


def norm_ang(a):
    a = int(round(a)) % 360
    if a < 0:
        a += 360
    return a


def fnum(v):
    r = round(v, 1)
    if r == int(r):
        return str(int(r))
    return ("%.1f" % r)


def load():
    return json.load(io.open(DATA, encoding="utf-8"))


def seed_thread(mapname, rec):
    L = ["seed_%s:" % mapname, "{"]
    na = nt = nj = nn = nf = 0
    for c in rec.get("at_crates", []):
        # team is resolved at pickup time (nationality of the picker); the authored "type" only hints the
        # crate's original side, so we pass it as the DEFAULT/back-compat type.
        L.append('\twaitthread coop_mod/mp_vehicles.scr::veh_at ( %s %s %s ) %d "%s"'
                 % (fnum(c["x"]), fnum(c["y"]), fnum(c["z"]), norm_ang(c["yaw"]), c["type"]))
        na += 1
    for t in rec.get("tanks", []):
        L.append('\twaitthread coop_mod/mp_vehicles.scr::veh_tank ( %s %s %s ) %d "%s" "%s"'
                 % (fnum(t["x"]), fnum(t["y"]), fnum(t["z"]), norm_ang(t["yaw"]), t["model"], t["team"]))
        nt += 1
    for j in rec.get("jeeps", []):
        L.append('\twaitthread coop_mod/mp_vehicles.scr::veh_jeep ( %s %s %s ) %d'
                 % (fnum(j["x"]), fnum(j["y"]), fnum(j["z"]), norm_ang(j["yaw"])))
        nj += 1
    for n in rec.get("nebelwerfers", []):
        L.append('\twaitthread coop_mod/mp_vehicles.scr::veh_nebelwerfer ( %s %s %s ) %d'
                 % (fnum(n["x"]), fnum(n["y"]), fnum(n["z"]), norm_ang(n["yaw"])))
        nn += 1
    for f in rec.get("flak", []):
        L.append('\twaitthread coop_mod/mp_vehicles.scr::veh_flak ( %s %s %s ) %d'
                 % (fnum(f["x"]), fnum(f["y"]), fnum(f["z"]), norm_ang(f["yaw"])))
        nf += 1
    L.append('\tprintln( "^~^~^ MPVEHMAP seeded %s at=%d tank=%d jeep=%d neb=%d flak=%d" )'
             % (mapname, na, nt, nj, nn, nf))
    L.append("}end")
    return "\n".join(L)


def render(data):
    present = [m for m in ORDER if m in data]
    L = [
        "//GENERATED by docs/tools/gen_vehicle_maps.py -- DO NOT HAND-EDIT (regenerate instead).",
        "//Authored MP vehicle/emplacement placements for the 5 SP campaign maps UberMod's vehicle system",
        "//shipped on. Coordinates harvested from OwN-3m-All UberMod V5 base_assault/maps/*.scr (by ViPER);",
        "//this is an MP-isolated rebuild. coop_mod/mp_vehicles.scr owns the spawner labels called below.",
        "//coop_mpRun-guarded; a compile canary on every MP boot.",
        "alive:{",
        "\tend 1",
        "}end",
        "",
        "//Spawn the authored vehicle layout for the current map (lowercased mapname). Returns 1 if this map",
        "//has an authored layout, 0 otherwise.",
        "seed local.map:{",
        "\tif( level.coop_mpRun != 1 ){ end 0 }",
        "\tlevel.coop_mpVehSeeded = 0",
        "\tswitch( local.map ){",
    ]
    for m in present:
        L.append('\t\tcase "%s":' % m)
        L.append("\t\t\twaitthread seed_%s" % m)
        L.append("\t\t\tlevel.coop_mpVehSeeded = 1")
        L.append("\t\t\tbreak")
    L += [
        "\t}",
        "\tend level.coop_mpVehSeeded",
        "}end level.coop_mpVehSeeded",
        "",
    ]
    for m in present:
        L.append(seed_thread(m, data[m]))
        L.append("")
    return "\n".join(L).rstrip("\n") + "\n"


def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else "check"
    data = load()
    text = render(data)
    try:
        text.encode("ascii")
    except UnicodeEncodeError:
        raise SystemExit("gen_vehicle_maps: output is not ASCII")
    if mode == "build":
        io.open(OUT, "wb").write(text.encode("ascii"))
        print("wrote %s (%d bytes)" % (os.path.relpath(OUT, ROOT), len(text)))
        return 0
    if not os.path.exists(OUT):
        print("MISSING %s - run: python docs/tools/gen_vehicle_maps.py build" % os.path.relpath(OUT, ROOT))
        return 1
    cur = io.open(OUT, "r", encoding="latin-1", newline="").read()
    if cur == text:
        print("EXACT REPRODUCTION (%s)" % os.path.relpath(OUT, ROOT))
        return 0
    print("DRIFT - run: python docs/tools/gen_vehicle_maps.py build")
    return 1


if __name__ == "__main__":
    sys.exit(main())
