#!/usr/bin/env python3
"""Generate coop_mod/mp_arena_spawns.scr - shared MP team spawns for the SP campaign maps that are
launched as script-less arenas (sv_mpForceArena) and therefore have NO player spawns of their own.

The spawn coordinates are REUSED from the already-authored Base Assault and Push layouts (both spawn
info_player_allied AND info_player_axis), so Build-A-Base / Cyber Attack / Search & Destroy can run on
those same 11 campaign maps without hand-authoring new spawns. This generator EXTRACTS just the plain
team spawn points (origin + angle) from those two generated files - it drops their mode-specific
targetnames and level vars - and emits ensureSpawns(map), which the three loaders call before the mode
starts. Regenerate whenever the source layouts change; a byte-identical check gates the build.

Map ownership: Base Assault provides m1l3a m1l3b m4l1 m5l2a m5l3; Push provides m1l2b m2l1 m3l3 m4l2
m5l1a m5l1b. (m4l1 is in both; Base Assault wins.)

Run:  python docs/tools/gen_arena_spawns.py         (write)
      python docs/tools/gen_arena_spawns.py check   (exit 1 if the .scr is stale)
"""
import sys, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
COOP = os.path.join(ROOT, "hzm-mohaa-coop-mod", "coop_mod")
BA = os.path.join(COOP, "mp_baseassault_maps.scr")
PUSH = os.path.join(COOP, "mp_push_maps.scr")
OUT = os.path.join(COOP, "mp_arena_spawns.scr")

# which source owns each campaign map (Base Assault wins the m4l1 overlap)
OWNER = {
    "m1l3a": BA, "m1l3b": BA, "m4l1": BA, "m5l2a": BA, "m5l3": BA,
    "m1l2b": PUSH, "m2l1": PUSH, "m3l3": PUSH, "m4l2": PUSH, "m5l1a": PUSH, "m5l1b": PUSH,
}
ORDER = ["m1l2b", "m1l3a", "m1l3b", "m2l1", "m3l3", "m4l1", "m4l2", "m5l1a", "m5l1b", "m5l2a", "m5l3"]


def seed_block(text, mapname):
    """Return the lines of the seed_<map> function body (between its label and the next col-0 label)."""
    lines = text.splitlines()
    out, grab = [], False
    for l in lines:
        if re.match(r'^seed_%s\b' % re.escape(mapname), l):
            grab = True
            continue
        if grab and re.match(r'^[A-Za-z_]\w*\s*:', l):  # next label at col 0 -> stop
            break
        if grab:
            out.append(l)
    return out


def extract_spawns(body):
    """From a seed body, yield (team, origin, angle) for each info_player_allied/axis spawn."""
    team = None
    origin = None
    for l in body:
        m = re.search(r'spawn\s+info_player_(allied|axis)', l)
        if m:
            team, origin = m.group(1), None
            continue
        if team is not None:
            mo = re.search(r'\.origin\s*=\s*(\([^)]*\))', l)
            if mo:
                origin = mo.group(1).strip()
                continue
            ma = re.search(r'\.angle\s*=\s*(-?\d+(?:\.\d+)?)', l)
            if ma and origin is not None:
                yield (team, origin, ma.group(1))
                team, origin = None, None


def build():
    ba_txt = open(BA, encoding="latin-1").read()
    push_txt = open(PUSH, encoding="latin-1").read()
    src = {BA: ba_txt, PUSH: push_txt}

    per_map = {}
    for m in ORDER:
        body = seed_block(src[OWNER[m]], m)
        per_map[m] = list(extract_spawns(body))

    L = []
    L.append("// GENERATED by docs/tools/gen_arena_spawns.py. Do NOT hand-edit.")
    L.append("// Shared MP team spawns for the SP campaign maps run as script-less arenas (sv_mpForceArena),")
    L.append("// whose bsps carry no MP spawns. Coordinates are REUSED from the authored Base Assault + Push")
    L.append("// layouts (info_player_allied + info_player_axis), so Build-A-Base / Cyber Attack / Search &")
    L.append("// Destroy can run on the same 11 campaign maps without new spawn authoring. The three loaders")
    L.append("// call ensureSpawns(map) before the mode starts; on the mohdm* deathmatch maps (which already")
    L.append("// carry bsp spawns) the map is simply absent from the switch and this is a no-op.")
    L.append("// MP-only (coop_mod/mp*.scr, guarded by level.coop_mpRun); never touches coop.")
    L.append("")
    L.append("//canary")
    L.append("alive:{")
    L.append("\tend 1")
    L.append("}end")
    L.append("")
    L.append("//spawn this map's reused MP team spawns, if it is one of the authored campaign maps (else no-op).")
    L.append("ensureSpawns local.map:{")
    L.append("\tif( level.coop_mpRun != 1 ){ end }")
    L.append("\tswitch( local.map ){")
    for m in ORDER:
        if not per_map[m]:
            continue
        L.append('\tcase "%s":' % m)
        L.append("\t\twaitthread spawn_%s" % m)
        L.append('\t\tprintln( "^~^~^ MP arena spawns injected map=%s n=%d" )' % (m, len(per_map[m])))
        L.append("\t\tbreak")
    L.append("\t}")
    L.append("}end")
    for m in ORDER:
        spawns = per_map[m]
        if not spawns:
            continue
        L.append("")
        L.append("")
        L.append("spawn_%s:{" % m)
        for team, origin, angle in spawns:
            L.append("\tlocal.e = spawn info_player_%s" % team)
            L.append("\tlocal.e.origin = %s" % origin)
            L.append("\tlocal.e.angle = %s" % angle)
        L.append("}end")
    L.append("")
    return "\n".join(L), per_map


def main():
    text, per_map = build()
    if len(sys.argv) > 1 and sys.argv[1] == "check":
        cur = open(OUT, encoding="latin-1").read() if os.path.exists(OUT) else ""
        if cur != text:
            print("STALE: mp_arena_spawns.scr differs from generator output")
            sys.exit(1)
        print("OK: mp_arena_spawns.scr matches generator")
        return
    open(OUT, "w", encoding="latin-1", newline="\n").write(text)
    tot = sum(len(v) for v in per_map.values())
    print("wrote %s (%d maps, %d spawns)" % (os.path.relpath(OUT, ROOT), sum(1 for v in per_map.values() if v), tot))


if __name__ == "__main__":
    main()
