#!/usr/bin/env python3
"""Generate ui/hzm_arenamaps.urc - the shared campaign/arena MAP PICKER for the three UberMod modes that
run on script-less MP arenas: Build-A-Base, Cyber Attack, Search & Destroy.

All three support the SAME 18 maps: the 7 mohdm* deathmatch maps (bsp spawns) + the 11 SP campaign maps
that have reused Base Assault / Push team spawns. Each button arms the one-shot engine arena gate
sv_mpForceArena and sets ui_dmmap, exactly like the Base Assault (hzm_bamaps) and Push (hzm_pushmaps)
pickers. The board opens this via one "Campaign Maps" button gated by ui_mpIsArena (set only by these three
modes' start_*.cfg). Isolation-clean: sets only ui_dmmap + sv_mpForceArena.

The map list is the SINGLE source of truth for what these modes offer (Stage 3: no mode offers an
unsupported map). Keep it in sync with basebuild_stations.tsv / cybersnd_sites.tsv + mp_arena_spawns.scr.

Run:  python docs/tools/gen_arenamaps_menu.py         (write)
      python docs/tools/gen_arenamaps_menu.py check   (exit 1 if the .urc is stale)
"""
import sys, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, "hzm-mohaa-coop-mod", "ui", "hzm_arenamaps.urc")


def loadpath(m):
    """The value ui_dmmap needs to actually load the bsp. mohdm* live in maps/DM/, so they need the
    "dm/" prefix (and the engine's mapname cvar then reads "dm/mohdm1"); campaign maps load bare."""
    return "dm/" + m if re.match(r"^mohdm\d", m) else m

# (mapname, button label). Order: 7 mohdm deathmatch maps, then the 11 reused-spawn campaign maps.
MAPS = [
    ("mohdm1", "Southern France"), ("mohdm2", "Destroyed Village"), ("mohdm3", "Remagen"),
    ("mohdm4", "The Bridge"), ("mohdm5", "Stalingrad"), ("mohdm6", "Snowy Park"),
    ("mohdm7", "Algiers"),
    ("m1l2b", "Mission 1-2b"), ("m1l3a", "Mission 1-3a"), ("m1l3b", "Mission 1-3b"),
    ("m2l1", "Mission 2-1"), ("m3l3", "Mission 3-3"), ("m4l1", "Mission 4-1"),
    ("m4l2", "Mission 4-2"), ("m5l1a", "Mission 5-1a"), ("m5l1b", "Mission 5-1b"),
    ("m5l2a", "Mission 5-2a"), ("m5l3", "Mission 5-3"),
]

COLS = 3
COL_X = [104, 258, 412]
BTN_W = 146
ROW_Y0 = 124
ROW_DY = 34
BTN_H = 30


def build():
    L = []
    L.append("// GENERATED by docs/tools/gen_arenamaps_menu.py. Do NOT hand-edit (regenerate instead).")
    L.append("// Shared campaign/arena MAP PICKER for Build-A-Base / Cyber Attack / Search & Destroy. Each")
    L.append("// button arms the one-shot engine arena gate sv_mpForceArena and sets ui_dmmap, so the mode's")
    L.append("// map is launched as a script-less MP arena (the mohdm* maps carry bsp spawns; the campaign maps")
    L.append("// use the reused Base Assault/Push spawns in mp_arena_spawns.scr). Reached from the team board's")
    L.append("// 'Campaign Maps' button, which is gated by ui_mpIsArena. Sets only ui_dmmap + sv_mpForceArena.")
    L.append('menu "hzm_arenamaps" 640 480 NONE 0')
    L.append("bgcolor 1 1 1 1")
    L.append("borderstyle NONE")
    L.append("bgfill 0 0 0 1")
    L.append("fullscreen 1")
    L.append("virtualres 1")
    L.append('include "ui/multiplayerback.inc"')
    # panel
    L += ["resource", "Label", "{", 'name "bg_panel"', "rect 84 56 472 372",
          "fgcolor 0.84 0.82 0.76 1.00", "bgcolor 0.05 0.06 0.08 1.00", 'borderstyle "RAISED"', "}"]
    # caption
    L += ["resource", "Label", "{", 'name "caption"', 'title "SELECT ARENA MAP"',
          "rect 84 66 472 22", "fgcolor 0.86 0.74 0.44 1.00", "bgcolor 0.00 0.00 0.00 0.00",
          'borderstyle "NONE"', 'font "facfont-20"', "textalign xcenter", "}"]
    # subtitle
    L += ["resource", "Label", "{", 'name "sub"',
          'title "Build-A-Base / Cyber Attack / Search & Destroy maps"',
          "rect 84 92 472 16", "fgcolor 0.55 0.60 0.66 1.00", "bgcolor 0.00 0.00 0.00 0.00",
          'borderstyle "NONE"', 'font "verdana-12"', "textalign xcenter", "}"]
    # map buttons
    for i, (m, label) in enumerate(MAPS):
        col = i % COLS
        row = i // COLS
        x = COL_X[col]
        y = ROW_Y0 + row * ROW_DY
        L += ["resource", "Button", "{",
              'name "map_%s"' % m,
              'title "%s"' % label,
              "rect %d %d %d %d" % (x, y, BTN_W, BTN_H),
              "fgcolor 1.00 1.00 1.00 1.00", "bgcolor 0.09 0.10 0.13 0.90",
              'borderstyle "3D_BORDER"', 'font "verdana-12"',
              'clicksound "sound/menu/apply.wav"',
              'stuffcommand "set sv_mpForceArena 1 ; set ui_dmmap %s ; popmenu 0"' % loadpath(m),
              "}"]
    # hint
    L += ["resource", "Label", "{", 'name "hint"',
          'title "Pick a map, then Start Game."',
          "rect 84 344 472 16", "fgcolor 0.55 0.60 0.66 1.00", "bgcolor 0.00 0.00 0.00 0.00",
          'borderstyle "NONE"', 'font "verdana-12"', "textalign xcenter", "}"]
    # back
    L += ["resource", "Button", "{", 'name "back"', "rect 8 448 96 24",
          "fgcolor 1.00 1.00 1.00 1.00", "bgcolor 0.50 0.50 0.50 0.00", 'borderstyle "3D_BORDER"',
          'shader "textures/mohmenu/back"', 'hovershader "textures/mohmenu/back_h"',
          'clicksound "sound/menu/back.wav"', 'stuffcommand "Popmenu 0"', "}"]
    L.append("end.")
    return "\n".join(L) + "\n"


def main():
    text = build()
    if len(sys.argv) > 1 and sys.argv[1] == "check":
        cur = open(OUT, encoding="latin-1").read() if os.path.exists(OUT) else ""
        if cur != text:
            print("STALE: hzm_arenamaps.urc differs from generator output")
            sys.exit(1)
        print("OK: hzm_arenamaps.urc matches generator")
        return
    open(OUT, "w", encoding="latin-1", newline="\n").write(text)
    print("wrote %s (%d maps)" % (os.path.relpath(OUT, ROOT), len(MAPS)))


if __name__ == "__main__":
    main()
