"""Emit one challenge per WEAPON MODEL VARIANT, on an accelerating kill curve.

WHY THIS IS GENERATED. Before this, loadout_mvUnlocked checked a single cid - the gun's ELITE
challenge - and returned unlocked for that gun's ENTIRE variant cycle, so one challenge handed you
all eight Thompsons at once (user, 2026-08-26: "confirm that all skin variants have their own
challenges or ranks, and not just one single unlock challenge to get ALL variants").

THE RECIPE IS ALREADY IN THE TREE, for exactly one item:
    chal_def "wpn_thompson_gold" ... "Get 250 kills with the Thompson to unlock it in gold"
             "wpn_thompson" 250 "models/weapons/thompsonsmg_gold.tik"
Base 50 -> elite 150 -> gold 250. This extends that shape to all 77 variants instead of inventing
a second mechanism: same chal_def, same per-weapon kill stat, just more thresholds. NO NEW STAT
WRITERS ARE NEEDED, which is the whole reason this approach was chosen over 77 bespoke challenges.

CURVE. target(k) = B * (3 + k^1.3), rounded to 25, where B is that gun's OWN base challenge target.
Keying off B rather than a flat number keeps a sniper's 40-kill scale and an SMG's 50-kill scale
proportionate. Accelerating per the user's call, so the 11th Springfield variant is a genuine
long-tail chase rather than the 11th identical errand.

Rebuild:  python docs/tools/variant_challenges.py --emit
"""
import io, os, re, sys

ROOT   = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SKINS  = os.path.join(ROOT, "hzm-mohaa-coop-mod", "coop_mod", "loadoutskins.scr")
CHALS  = os.path.join(ROOT, "hzm-mohaa-coop-mod", "coop_mod", "challenges.scr")
OUT    = os.path.join(ROOT, "hzm-mohaa-coop-mod", "coop_mod", "mvchal_gen.scr")


def read(p):
    return io.open(p, encoding="utf-8", errors="replace").read()


def collect():
    s = read(SKINS)
    give  = re.findall(r'level\.coop_skinGive\["([^"]+)"\]\[(\d+)\]\s*=\s*"([^"]+)"', s)
    name  = dict(((g, int(f)), n) for g, f, n in
                 re.findall(r'level\.coop_skinMvName\["([^"]+)"\]\[(\d+)\]\s*=\s*"([^"]*)"', s))
    elite = dict(re.findall(r'level\.coop_skinMvElite\["([^"]+)"\]\s*=\s*"([^"]+)"', s))

    c = read(CHALS)
    # base challenges: chal_def "<cid>" "<cat>" "<title>" "<desc>" "<stat>" <target> "<reward>"
    base = {}
    for cid, cat, title, desc, stat, tgt, rew in re.findall(
            r'chal_def\s+"([^"]+)"\s+"([^"]+)"\s+"([^"]*)"\s+"([^"]*)"\s+"([^"]*)"\s+(\d+)\s+"([^"]*)"', c):
        base[cid] = (cat, stat, int(tgt))

    rows = []
    for gun, fid, path in give:
        fid = int(fid)
        if fid < 8:
            continue                      # 1-7 are FINISHES, gated separately and already per-gun
        ecid = elite.get(gun)
        if not ecid:
            continue
        bcid = ecid[:-2] if ecid.endswith("_e") else ecid
        if bcid not in base:
            continue                      # no base challenge => no kill stat => cannot gate on one
        cat, stat, btgt = base[bcid]
        rows.append(dict(gun=gun, fid=fid, path=path, cat=cat, stat=stat, btgt=btgt,
                         label=name.get((gun, fid), "").strip(), bcid=bcid))
    rows.sort(key=lambda r: (r["gun"], r["fid"]))
    return rows


CAP = 750   # [user 2026-08-26] "I think 1000 for any challenge may be too much, maybe like 750 max"


def curve_set(btgt, n):
    """Accelerating thresholds for a gun's n variants, last one landing at or under CAP.

    Clamping each value at CAP would pile the tail of a long cycle onto the SAME number - the
    Springfield's last four variants would all read 750 and the progression would stop meaning
    anything. Instead the whole set is remapped onto [first, CAP], which is a linear rescale of the
    same accelerating curve: the shape survives, the ceiling is respected, and every variant keeps a
    distinct threshold. Guns whose uncapped tail already sits under CAP are left exactly as they were.
    """
    raw = [btgt * (3.0 + (k ** 1.3)) for k in range(1, n + 1)]
    lo, hi = raw[0], raw[-1]
    if hi > CAP and hi > lo:
        raw = [lo + (CAP - lo) * ((v - lo) / (hi - lo)) for v in raw]
    return [max(25, int(round(v / 25.0)) * 25) for v in raw]


def gunword(bcid):
    return bcid[4:].replace("_", " ").title() if bcid.startswith("wpn_") else bcid


def emit(rows):
    L = []
    L.append("//=========================================================================")
    L.append("// GENERATED by docs/tools/variant_challenges.py --emit   DO NOT EDIT BY HAND")
    L.append("//=========================================================================")
    L.append("// One challenge PER MODEL VARIANT, on an accelerating per-gun kill curve.")
    L.append("// Replaces the old behaviour where a gun's single ELITE challenge unlocked its")
    L.append("// whole variant cycle at once. Rides each gun's EXISTING kill stat, so no new")
    L.append("// stat writers are introduced - only new thresholds on stats already written.")
    L.append("//=========================================================================")
    L.append("")
    L.append("main:{")
    L.append("\tif( level.coop_mvChalBuilt == 1 ){ end }")
    L.append("\tlevel.coop_mvChalBuilt = 1")
    L.append("")
    per = {}
    for r in rows:
        per.setdefault(r["gun"], []).append(r)
    for gun in sorted(per):
        vs = per[gun]
        L.append("\t//---- %s ----" % gun.replace("models/weapons/", ""))
        ordered = sorted(vs, key=lambda x: x["fid"])
        targets = curve_set(ordered[0]["btgt"], len(ordered))
        for k, r in enumerate(ordered, start=1):
            tgt = targets[k - 1]
            cid = "%s_mv%d" % (r["bcid"], r["fid"])
            word = gunword(r["bcid"])
            label = r["label"] or ("Variant %d" % r["fid"])
            label = label.replace('"', "'")
            title = ("%s Variant %d" % (word, k))[:46]
            desc  = "Get %d kills with the %s to unlock %s" % (tgt, word, label)
            desc  = desc[:118]
            L.append('\twaitthread coop_mod/challenges.scr::chal_def "%s" "%s" "%s" "%s" "%s" %d "%s"'
                     % (cid, r["cat"], title, desc, r["stat"], tgt, r["path"]))
            L.append('\tlevel.coop_skinMvChal["%s"][%d] = "%s"' % (gun, r["fid"], cid))
        L.append("")
    L.append("}end")
    L.append("")
    return "\n".join(L)


rows = collect()
txt = emit(rows)
bad = [c for c in txt if ord(c) > 127]
assert not bad, "non-ASCII in generated .scr is a parse killer: %r" % bad[:5]
if "--emit" in sys.argv:
    io.open(OUT, "w", encoding="utf-8", newline="\r\n").write(txt)
    print("wrote %s" % OUT)
print("variants gated: %d across %d guns" % (len(rows), len(set(r["gun"] for r in rows))))
