# -*- coding: utf-8 -*-
"""Map-usage table + Omaha exclusion proof for the m3l2 ground proposal (generated, not hand-written).

    python map_usage.py OUT.md [--pak ../staged/zzzzzzzzzz_coop_m3l2ground.pk3]
Scans every BSP of the PLAYER stack (retail paks + manifests/latest.json paks; gen_terrain_pak_v3.Stack) for the
shaders/images the proposal touches or could touch, then proves from the pak itself what it can change.
"""
import argparse, os, sys, zipfile
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import scene as SC                      # noqa: E402
import gen_terrain_pak_v3 as V3         # noqa: E402

OMAHA = ("maps/m3l1a.bsp", "maps/m3l1b.bsp", "maps/e3l1.bsp", "maps/e3l2.bsp", "maps/obj/obj_team3.bsp")
IMAGES = ["textures/wilderness/m3l3grass_bocroad_new", "textures/wilderness/m3l3grass_bocroad",
          "textures/misc_outside/bocage_stevereq", "textures/wilderness/m3l3grass_1rough",
          "textures/wilderness/m3l3grass_set2", "textures/wilderness/m3l3grass_set2rad"]
ROLE = {
    "textures/wilderness/m3l3grass_bocroad_new": "image of shader m3l3grass_bocroad (BT tanatural.shader) - m3l2 road + courtyard today. NOT changed: m3l2 stops using it; every other map keeps it byte-identical",
    "textures/wilderness/m3l3grass_bocroad": "AA image, shadowed by BT's remap (never drawn). NOT changed",
    "textures/misc_outside/bocage_stevereq": "m3l2 barnyard floor today (128 u repeat). NOT changed: m3l2's 8 barnyard faces stop using it; its other m3l2 faces and the MP maps keep it",
    "textures/wilderness/m3l3grass_1rough": "terrain grass beside the road. NOT changed (the road's shoulders are cut from it so they match)",
    "textures/wilderness/m3l3grass_set2": "barnyard rim / junction dirt. NOT changed (colour target of the new dirt)",
    "textures/wilderness/m3l3grass_set2rad": "bridge-junction dirt. NOT changed (colour target of the new dirt)",
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("out")
    ap.add_argument("--pak", default=os.path.join(HERE, "..", "staged", "zzzzzzzzzz_coop_m3l2ground.pk3"))
    a = ap.parse_args()
    st = SC.stack()
    use, nmaps, notes = V3.map_usage(st, IMAGES)
    L = ["# m3l2 ground - map usage and Omaha exclusion (generated by tools/map_usage.py)", "",
         "Player stack: retail paks + manifest %s paks; %d BSPs scanned." % (st.manifest_version, nmaps), "",
         "| image | maps that draw it (surfaces) | on an Omaha map? | role in this proposal |", "|---|---|---|---|"]
    for im in IMAGES:
        u = use[im]
        om = [m for m in u["maps"] if m in OMAHA]
        L.append("| `%s` | %s | %s | %s |" % (im.split("/", 1)[1], V3.usage_str(u), ", ".join(om) or "no", ROLE[im]))
    z = zipfile.ZipFile(a.pak)
    names = sorted(z.namelist())
    L += ["", "## What the pak can change", "", "Members of `%s`:" % os.path.basename(a.pak), ""]
    L += ["- `%s`" % n for n in names]
    retail_names = [n for n in names if n in st.copies]
    L += ["", "Members that already exist in the player stack (i.e. override something): %s" %
          (", ".join("`%s` (%s)" % (n, ", ".join(st.name(i) for i, m in st.copies[n])) for n in retail_names) or "none"),
          "", "Every other member is a NEW name. A BSP can only draw a shader it names:"]
    refs = []
    for p in sorted(k for k in st.copies if k.startswith("maps/") and k.endswith(".bsp")):
        i, m = st.winner(p)
        if b"hzm_m3l2" in st.read(i, m):
            refs.append(p)
    patched = z.read("maps/m3l2.bsp")
    L += ["", "- player-stack BSPs that name `textures/hzm_m3l2/*`: %s" % (", ".join(refs) or "**none**"),
          "- the patched `maps/m3l2.bsp` names them: %s" % ("yes" if b"textures/hzm_m3l2/farmyard" in patched else "NO"),
          "- Omaha maps in the pak: %s" % (", ".join(n for n in names if n in OMAHA) or "**none**"),
          "- Omaha-named members (omaha/ocean/seabed/wetsand/shoreline/surf/wake): %s" %
          (", ".join(n for n in names if V3.re.search(r"(omaha|ocean|seabed|wetsand|shoreline|surf|wake)", n))
           or "**none**"),
          "- `zzzzzzzzzz_coop_hd_m3l1a.pk3`, the dday2 sky: not read, not written, not overridden.", "",
          "**Conclusion:** the only file this pak overrides is m3l2's own map; every texture/shader it adds is a new "
          "name only that map uses. No other map - Omaha included - can render anything different."]
    open(a.out, "w", encoding="utf-8", newline="\n").write("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
