"""Build AUDIT_TABLE.md from inventory.json: every player weapon, grouped by base gun, with its skins/variants/finishes.

First person and third person draw the SAME weapon TIK (cg_modelanim.c re-parents the weapon entity onto the FPS
hands; there is no separate view-model texture), so one row covers both. "_lite" TIKs share the base sheet.
"""
import json, os, re, collections
HERE = os.path.dirname(os.path.abspath(__file__))
inv = json.load(open(os.path.join(HERE, "inventory.json")))
by = {t["tik"].split("/")[-1][:-4].lower(): t for t in inv}
FIN = ("bloody", "blued", "camo_desert", "camo_winter", "camo_woodland", "chrome", "gold")
STAGE_FIN = ("blued", "chrome", "gold")            # shader stages over the base diffuse (DECISIONS 2026-08-17)

weapons = {k: t for k, t in by.items() if t["weapon"]}
bases = sorted(k for k, t in weapons.items() if not t["finish"])


def base_of(k):
    best = None
    for b in bases:
        if k != b and k.startswith(b + "_") and (best is None or len(b) > len(best)):
            best = b
    return best


groups = collections.OrderedDict()
for k in bases:
    b = base_of(k)
    if b is None:
        groups.setdefault(k, {"variants": [], "finishes": collections.Counter()})
for k in bases:
    b = base_of(k)
    if b is not None:
        root = b
        while base_of(root):
            root = base_of(root)
        groups.setdefault(root, {"variants": [], "finishes": collections.Counter()})["variants"].append(k)
for k, t in weapons.items():
    if t["finish"]:
        stem = k[: -len(t["finish"]) - 1]
        root = stem
        while base_of(root):
            root = base_of(root)
        if root in groups:
            groups[root]["finishes"][t["finish"]] += 1


def sheets(t):
    out = collections.OrderedDict()
    for s in t["surfaces"]:
        for x in s["textures"]:
            if not x["loads"]:
                continue
            if "/common/" in x["loads"] or x["loads"].startswith("textures/effects/") or "env_sheen" in x["loads"]:
                continue
            i = x["info"] or {}
            out[x["loads"]] = (i.get("w"), i.get("h"), (i.get("fmt") or "").replace("dds/", ""), i.get("pak", ""),
                               [p for e, p in x["versions"]])
    return out


def status(w, h, pak, versions):
    m = max(w or 0, h or 0)
    hrr = "HRRTM" in pak
    if hrr:
        return "HD (HRRTM: 2048 DXT5 container, lossless art 1280-1792 in Pak4c)" if m >= 2048 else "HD (HRRTM)"
    if "hdmem" in pak or "dds_override" in pak:
        return "AI/upscale pak (%d)" % m
    if "m3l1a" in pak:
        return "4x upscale, Omaha pak (%d)" % m
    if m >= 1024:
        return "%d native" % m
    return "LOW (%d)" % m


def short(p):
    return (p.replace("zzzzzz_co-op_hzm_mod_assets_tex.pk3", "coop tex").replace("zzzzzz-HRRTM_Pak4_Weapons.pk3", "HRRTM Pak4")
            .replace("zzzzzzz_dds_hdmem.pk3", "dds_hdmem").replace("zzzzzzz_dds_override.pk3", "dds_override")
            .replace("zzzzz_xw_weapons.pk3", "xw_weapons").replace("zzzzzzzzzz_coop_hd_m3l1a.pk3", "hd_m3l1a (Omaha)"))


rows = []
tot = collections.Counter()
for g, d in groups.items():
    t = weapons[g]
    sh = sheets(t)
    vs = d["variants"]
    vres = []
    for v in vs:
        for p, (w, h, f, pak, _) in sheets(weapons[v]).items():
            if p not in sh:
                vres.append(max(w or 0, h or 0))
    fins = d["finishes"]
    baked = sum(n for f, n in fins.items() if f not in STAGE_FIN)
    first = True
    if not sh:
        rows.append("| %s | %s | - | - | - | - | %d | %s |" % (g, t["name"] or "", len(vs), ""))
        continue
    for p, (w, h, f, pak, vers) in sh.items():
        tot[status(w, h, pak, vers).split(" (")[0]] += 1
        rows.append("| %s | %s | `%s` | %sx%s %s | %s | %s | %s | %s |" % (
            g if first else "", (t["name"] or "") if first else "", p.replace("textures/models/weapons/", "~/"), w, h, f,
            short(pak), status(w, h, pak, vers),
            ("%d (%s)" % (len(vs), "%d-%d px" % (min(vres), max(vres)) if vres else "same sheet")) if first and vs else "",
            ("%d (%d baked)" % (sum(fins.values()), baked)) if first and fins else ""))
        first = False

hdr = ["| base TIK | name | sheet (1P = 3P) | loads today | won by | status | skin variants | finishes |",
       "|---|---|---|---|---|---|---|---|"]
open(os.path.join(HERE, "..", "AUDIT_TABLE.md"), "w", encoding="utf-8").write(
    "# Weapon texture audit - generated by tools/audit.py from tools/inventory.json\n\n"
    "%d base weapon TIKs, %d sheets. 1P and 3P draw the same TIK and texture (see AUDIT.md).\n\n" % (len(groups), len(rows))
    + "\n".join(hdr + rows) + "\n\nStatus counts: " + ", ".join("%s %d" % kv for kv in tot.most_common()) + "\n")
print(len(groups), "groups", len(rows), "rows", dict(tot))
