"""gen_wiring.py - generate the mod-side wiring for the new tiles into ../apply/mod/ (the live tree is only READ).

    python tools/gen_wiring.py

Writes (each file keeps the live file's own line endings, TRAPS T2):
  apply/mod/ui/coop_maps.inc         + two Labels BEFORE each coop_startMapN Button (declared first, so the Button stays on
                                     top for click + hover - hit-testing walks children last-to-first):
                                       coop_tileArtCN  linkcvar coop_tileArtN_c + linkcvartoshader, enabledcvar "ui_menuCenter"
                                       coop_tileArtSN  linkcvar coop_tileArtN_s + linkcvartoshader, enabledcvar "!ui_menuCenter"
  apply/mod/ui/coop_start/<m>.cfg    13 mission cfgs: tile Buttons transparent with a blank title, the art in the
                                     coop_tileArtN_{c,s} cvars (cvars are set whatever the layout, so a live
                                     ui_menuCenter switch is correct at once), click commands copied VERBATIM from the
                                     live cfg, mission header = titles.json. Slot 1 of e1-e3/t1-t3 = that campaign's own
                                     briefing card (bug-3274).
  apply/mod/ui/coop_start.urc        the dropdown labels (addpopup) -> the retail mission names (bug-3280/3284)
  apply/base.json                    md5 of every live file read, for apply.py --check
Unused slots get the cvar value menu_button_trans (a real transparent shader) - never "" (an unknown/empty shader name
would draw the engine's default image).
"""
import hashlib
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PROP = os.path.dirname(HERE)
MOD = r"C:\mohaa-coop-dev\hzm-mohaa-coop-mod"
OUT = os.path.join(PROP, "apply", "mod")
PREFIX = "textures/mohmenu/hzmtile/"
NSLOT = 11

HEADERS = {"m0": "Training / Secret", "m1": "1 - %s", "m2": "2 - %s", "m3": "3 - %s", "m4": "4 - %s", "m5": "5 - %s",
           "m6": "6 - %s", "e1": "Breakthrough 1 - %s", "e2": "Breakthrough 2 - %s", "e3": "Breakthrough 3 - %s",
           "t1": "Spearhead 1 - %s", "t2": "Spearhead 2 - %s", "t3": "Spearhead 3 - %s"}
DROPDOWN = {"m1": "Allied Assault: 1 %s", "m2": "Allied Assault: 2 %s", "m3": "Allied Assault: 3 %s",
            "m4": "Allied Assault: 4 %s", "m5": "Allied Assault: 5 %s", "m6": "Allied Assault: 6 %s",
            "e1": "Breakthrough: 1 %s", "e2": "Breakthrough: 2 %s", "e3": "Breakthrough: 3 %s",
            "t1": "Spearhead: 1 %s", "t2": "Spearhead: 2 %s", "t3": "Spearhead: 3 %s"}


def tid(bsp):
    return bsp.replace("/", "_").lower()


def rd(p):
    b = open(p, "rb").read()
    nl = "\r\n" if b.count(b"\r\n") > (b.count(b"\n") - b.count(b"\r\n")) else "\n"
    return b.decode("latin-1").replace("\r\n", "\n"), nl, hashlib.md5(b).hexdigest()


def wr(p, text, nl):
    os.makedirs(os.path.dirname(p), exist_ok=True)
    open(p, "wb").write(text.replace("\n", nl).encode("latin-1"))


def live_commands(cfg_text):
    live = "\n".join(l for l in cfg_text.split("\n") if not l.strip().startswith("//"))
    out = {}
    for n in range(1, NSLOT + 1):
        m = re.search(r'globalwidgetcommand coop_startMap%d stuffcommand ("(?:[^"]*)")' % n, live)
        out[n] = m.group(1) if m else '""'
    return out


def gen_cfg(cfg, slots, titles, missions, text):
    cmds = live_commands(text)
    head = HEADERS[cfg] % missions[cfg]["proposed"] if "%s" in HEADERS[cfg] else HEADERS[cfg]
    L = ["//HZM coop - GENERATED by docs/proposals/mission_tile_art_2026-09-29/tools/gen_wiring.py - do not hand-edit.",
         "//Mission tiles: each coop_startMapN Button is the click target; its art is drawn by the Labels under it",
         "//(ui/coop_maps.inc) from the coop_tileArtN_c / _s cvars, one per menu layout (ui_menuCenter 1 / 0).",
         "",
         "exec ui/coop_start/disableInfo.cfg",
         "",
         'globalwidgetcommand coop_missionName title "%s"' % head, ""]
    byslot = {s["slot"]: s for s in slots}
    for n in range(1, NSLOT + 1):
        s = byslot.get(n)
        L.append('globalwidgetcommand coop_startMap%d title " "' % n)
        L.append("globalwidgetcommand coop_startMap%d shader menu_button_trans" % n)
        if s:
            i = tid(s["bsp"])
            L.append("//%s - %s" % (s["bsp"], titles[s["bsp"]]["title"]))
            L.append("set coop_tileArt%d_c %s%s_c" % (n, PREFIX, i))
            L.append("set coop_tileArt%d_s %s%s_s" % (n, PREFIX, i))
            assert cmds[n] != '""', "%s slot %d has a tile but no live click command" % (cfg, n)
            L.append("globalwidgetcommand coop_startMap%d stuffcommand %s" % (n, cmds[n]))
        else:
            L.append("set coop_tileArt%d_c menu_button_trans" % n)
            L.append("set coop_tileArt%d_s menu_button_trans" % n)
            L.append('globalwidgetcommand coop_startMap%d stuffcommand ""' % n)
        L.append("")
    return "\n".join(L)


LABEL = """resource
Label
{
	name "coop_tileArt%(L)s%(n)d"
	rect %(rect)s
	fgcolor 1.00 1.00 1.00 1.00
	bgcolor 0.00 0.00 0.00 0.00
	borderstyle "NONE"
	linkcvar "coop_tileArt%(n)d_%(l)s"
	linkcvartoshader
	enabledcvar "%(gate)s"
}
"""


def gen_inc(text):
    out = text
    n_done = 0
    for n in range(1, NSLOT + 1):
        m = re.search(r'resource\nButton\n\{\n\ttitle ""\n\tname "coop_startMap%d"\n\trect ([0-9 ]+)\n' % n, out)
        assert m, "coop_startMap%d block not found" % n
        rect = m.group(1).strip()
        lab = (LABEL % {"L": "C", "n": n, "rect": rect, "l": "c", "gate": "ui_menuCenter"} +
               LABEL % {"L": "S", "n": n, "rect": rect, "l": "s", "gate": "!ui_menuCenter"})
        out = out[:m.start()] + "//[mission tile art] the tile's art, one Label per menu layout; the Button below stays the click target\n" \
            + lab + out[m.start():]
        n_done += 1
    assert n_done == NSLOT
    assert out.count("linkcvartoshader") == 2 * NSLOT
    return out


def main():
    inv = json.load(open(os.path.join(PROP, "inventory.json"), encoding="utf-8"))
    tj = json.load(open(os.path.join(HERE, "titles.json"), encoding="utf-8"))
    titles, missions = tj["tiles"], tj["missions"]
    base = {}
    # cfgs
    for m in inv["missions"]:
        cfg = m["cfg"]
        p = os.path.join(MOD, "ui", "coop_start", cfg + ".cfg")
        text, nl, h = rd(p)
        base["ui/coop_start/%s.cfg" % cfg] = h
        slots = [t for t in inv["tiles"] if t["cfg"] == cfg]
        wr(os.path.join(OUT, "ui", "coop_start", cfg + ".cfg"), gen_cfg(cfg, slots, titles, missions, text), nl)
    # the bug-3274 check: no BT/SH slot 1 may keep AA mission 1's Torch map
    for cfg in ("e1", "e2", "e3", "t1", "t2", "t3"):
        t = open(os.path.join(OUT, "ui", "coop_start", cfg + ".cfg"), encoding="latin-1").read()
        assert "briefing/briefing1" not in t.replace("briefing/briefing" + cfg, ""), cfg
        assert "hzmtile/briefing_briefing%s_" % cfg in t, cfg
    # coop_maps.inc
    p = os.path.join(MOD, "ui", "coop_maps.inc")
    text, nl, h = rd(p)
    base["ui/coop_maps.inc"] = h
    wr(os.path.join(OUT, "ui", "coop_maps.inc"), gen_inc(text), nl)
    # dropdown
    p = os.path.join(MOD, "ui", "coop_start.urc")
    text, nl, h = rd(p)
    base["ui/coop_start.urc"] = h
    n = 0
    for cfg, fmt in DROPDOWN.items():
        pat = r'(addpopup "MENU" ")([^"]+)(" command "exec ui/coop_start/%s\.cfg")' % cfg
        assert len(re.findall(pat, text)) == 1, cfg
        text = re.sub(pat, lambda mm: mm.group(1) + fmt % missions[cfg]["proposed"] + mm.group(3), text)
        n += 1
    wr(os.path.join(OUT, "ui", "coop_start.urc"), text, nl)
    json.dump(base, open(os.path.join(PROP, "apply", "base.json"), "w"), indent=1, sort_keys=True)
    print("wiring: %d cfgs, coop_maps.inc (+%d labels), %d dropdown labels" % (len(inv["missions"]), 2 * NSLOT, n))


if __name__ == "__main__":
    sys.exit(main())
